--
-- PostgreSQL database dump
--

\restrict qohQLkqyIv6itE424VhhsJ3hSRwUshrOyCcrFHUhrAtdvsosR9FM40Amlj8sL41

-- Dumped from database version 16.14 (Debian 16.14-1.pgdg13+1)
-- Dumped by pg_dump version 16.14 (Debian 16.14-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: applications; Type: TABLE; Schema: public; Owner: luisg
--

CREATE TABLE public.applications (
    id uuid NOT NULL,
    status character varying(8) NOT NULL,
    created timestamp with time zone NOT NULL,
    modified timestamp with time zone NOT NULL,
    creator_id uuid NOT NULL,
    modifier_id uuid,
    candidate_id uuid NOT NULL,
    offer_id uuid NOT NULL
);


ALTER TABLE public.applications OWNER TO luisg;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: luisg
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO luisg;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: luisg
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: luisg
--

CREATE TABLE public.auth_group_permissions (
    id integer NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO luisg;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: luisg
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: luisg
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO luisg;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: luisg
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: candidates; Type: TABLE; Schema: public; Owner: luisg
--

CREATE TABLE public.candidates (
    id uuid NOT NULL,
    description character varying(500),
    seniority character varying(7) NOT NULL,
    experience_years integer NOT NULL,
    status boolean NOT NULL,
    created timestamp with time zone NOT NULL,
    modified timestamp with time zone NOT NULL,
    creator_id uuid NOT NULL,
    modifier_id uuid NOT NULL,
    user_id uuid NOT NULL
);


ALTER TABLE public.candidates OWNER TO luisg;

--
-- Name: companies; Type: TABLE; Schema: public; Owner: luisg
--

CREATE TABLE public.companies (
    id uuid NOT NULL,
    name character varying(255) NOT NULL,
    status boolean NOT NULL,
    created timestamp with time zone NOT NULL,
    modified timestamp with time zone NOT NULL,
    creator_id uuid,
    modifier_id uuid
);


ALTER TABLE public.companies OWNER TO luisg;

--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: luisg
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id uuid NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO luisg;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: luisg
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: luisg
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO luisg;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: luisg
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: luisg
--

CREATE TABLE public.django_migrations (
    id integer NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO luisg;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: luisg
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: luisg
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO luisg;

--
-- Name: locations; Type: TABLE; Schema: public; Owner: luisg
--

CREATE TABLE public.locations (
    id uuid NOT NULL,
    name character varying(100) NOT NULL,
    status boolean NOT NULL,
    created timestamp with time zone NOT NULL,
    modified timestamp with time zone NOT NULL,
    creator_id uuid,
    modifier_id uuid
);


ALTER TABLE public.locations OWNER TO luisg;

--
-- Name: offers; Type: TABLE; Schema: public; Owner: luisg
--

CREATE TABLE public.offers (
    id uuid NOT NULL,
    title character varying(255) NOT NULL,
    description character varying(500) NOT NULL,
    modality character varying(10) NOT NULL,
    seniority character varying(7) NOT NULL,
    status boolean NOT NULL,
    salary numeric(10,2),
    created timestamp with time zone NOT NULL,
    modified timestamp with time zone NOT NULL,
    creator_id uuid NOT NULL,
    location_id uuid NOT NULL,
    modifier_id uuid,
    recruiter_id uuid NOT NULL
);


ALTER TABLE public.offers OWNER TO luisg;

--
-- Name: offers_technologies; Type: TABLE; Schema: public; Owner: luisg
--

CREATE TABLE public.offers_technologies (
    id uuid NOT NULL,
    offer_id uuid NOT NULL,
    technology_id uuid NOT NULL
);


ALTER TABLE public.offers_technologies OWNER TO luisg;

--
-- Name: recruiters; Type: TABLE; Schema: public; Owner: luisg
--

CREATE TABLE public.recruiters (
    id uuid NOT NULL,
    description character varying(500),
    contact_email character varying(254) NOT NULL,
    status boolean NOT NULL,
    created timestamp with time zone NOT NULL,
    modified timestamp with time zone NOT NULL,
    company_id uuid NOT NULL,
    creator_id uuid NOT NULL,
    modifier_id uuid NOT NULL,
    user_id uuid NOT NULL
);


ALTER TABLE public.recruiters OWNER TO luisg;

--
-- Name: technologies; Type: TABLE; Schema: public; Owner: luisg
--

CREATE TABLE public.technologies (
    id uuid NOT NULL,
    name character varying(100) NOT NULL,
    status boolean NOT NULL,
    created timestamp with time zone NOT NULL,
    modified timestamp with time zone NOT NULL,
    creator_id uuid,
    modifier_id uuid
);


ALTER TABLE public.technologies OWNER TO luisg;

--
-- Name: token_blacklist_blacklistedtoken; Type: TABLE; Schema: public; Owner: luisg
--

CREATE TABLE public.token_blacklist_blacklistedtoken (
    id bigint NOT NULL,
    blacklisted_at timestamp with time zone NOT NULL,
    token_id bigint NOT NULL
);


ALTER TABLE public.token_blacklist_blacklistedtoken OWNER TO luisg;

--
-- Name: token_blacklist_blacklistedtoken_id_seq; Type: SEQUENCE; Schema: public; Owner: luisg
--

ALTER TABLE public.token_blacklist_blacklistedtoken ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.token_blacklist_blacklistedtoken_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: token_blacklist_outstandingtoken; Type: TABLE; Schema: public; Owner: luisg
--

CREATE TABLE public.token_blacklist_outstandingtoken (
    id bigint NOT NULL,
    token text NOT NULL,
    created_at timestamp with time zone,
    expires_at timestamp with time zone NOT NULL,
    user_id uuid,
    jti character varying(255) NOT NULL
);


ALTER TABLE public.token_blacklist_outstandingtoken OWNER TO luisg;

--
-- Name: token_blacklist_outstandingtoken_id_seq; Type: SEQUENCE; Schema: public; Owner: luisg
--

ALTER TABLE public.token_blacklist_outstandingtoken ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.token_blacklist_outstandingtoken_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: luisg
--

CREATE TABLE public.users (
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    id uuid NOT NULL,
    modified timestamp with time zone NOT NULL,
    creator_id uuid,
    modifier_id uuid
);


ALTER TABLE public.users OWNER TO luisg;

--
-- Name: users_groups; Type: TABLE; Schema: public; Owner: luisg
--

CREATE TABLE public.users_groups (
    id integer NOT NULL,
    user_id uuid NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.users_groups OWNER TO luisg;

--
-- Name: users_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: luisg
--

ALTER TABLE public.users_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_user_permissions; Type: TABLE; Schema: public; Owner: luisg
--

CREATE TABLE public.users_user_permissions (
    id integer NOT NULL,
    user_id uuid NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.users_user_permissions OWNER TO luisg;

--
-- Name: users_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: luisg
--

ALTER TABLE public.users_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: applications; Type: TABLE DATA; Schema: public; Owner: luisg
--

COPY public.applications (id, status, created, modified, creator_id, modifier_id, candidate_id, offer_id) FROM stdin;
f8e8955f-3336-4233-92ce-05fb6a0c76aa	pending	2026-06-30 15:57:32.630976+00	2026-06-30 15:57:32.630987+00	91300142-f861-40ff-8910-e413ed0c6b57	91300142-f861-40ff-8910-e413ed0c6b57	bef535f0-281a-493f-aade-ae4d8625f60e	a2619fdb-6161-4639-96d0-44f98f56dcc7
0fcc193c-5a50-4860-ba35-ce519909be2c	pending	2026-06-30 15:58:04.499427+00	2026-06-30 15:58:04.499444+00	91300142-f861-40ff-8910-e413ed0c6b57	91300142-f861-40ff-8910-e413ed0c6b57	bef535f0-281a-493f-aade-ae4d8625f60e	6764f58b-15f3-4cfe-b8db-a6ec05165a9f
40539a54-bec0-4082-8782-80a4ba4ccd0c	pending	2026-06-30 16:01:03.308254+00	2026-06-30 16:01:03.308268+00	62826344-37f2-4166-b8cb-ec428b49c131	62826344-37f2-4166-b8cb-ec428b49c131	b010f66b-a4d2-4c7a-9364-46c8ac980d4c	6764f58b-15f3-4cfe-b8db-a6ec05165a9f
20ce6f5d-9738-4f14-a795-db064a5aa4dd	pending	2026-06-30 16:01:23.650868+00	2026-06-30 16:01:23.65088+00	62826344-37f2-4166-b8cb-ec428b49c131	62826344-37f2-4166-b8cb-ec428b49c131	b010f66b-a4d2-4c7a-9364-46c8ac980d4c	b4f20ed9-125f-4799-91f2-df44d8174c2d
\.


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: luisg
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: luisg
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: luisg
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add content type	4	add_contenttype
14	Can change content type	4	change_contenttype
15	Can delete content type	4	delete_contenttype
16	Can view content type	4	view_contenttype
17	Can add session	5	add_session
18	Can change session	5	change_session
19	Can delete session	5	delete_session
20	Can view session	5	view_session
21	Can add user	6	add_user
22	Can change user	6	change_user
23	Can delete user	6	delete_user
24	Can view user	6	view_user
25	Can add candidate	7	add_candidate
26	Can change candidate	7	change_candidate
27	Can delete candidate	7	delete_candidate
28	Can view candidate	7	view_candidate
29	Can add company	8	add_company
30	Can change company	8	change_company
31	Can delete company	8	delete_company
32	Can view company	8	view_company
33	Can add location	9	add_location
34	Can change location	9	change_location
35	Can delete location	9	delete_location
36	Can view location	9	view_location
37	Can add offer	10	add_offer
38	Can change offer	10	change_offer
39	Can delete offer	10	delete_offer
40	Can view offer	10	view_offer
41	Can add application	11	add_application
42	Can change application	11	change_application
43	Can delete application	11	delete_application
44	Can view application	11	view_application
45	Can add recruiter	12	add_recruiter
46	Can change recruiter	12	change_recruiter
47	Can delete recruiter	12	delete_recruiter
48	Can view recruiter	12	view_recruiter
49	Can add technology	13	add_technology
50	Can change technology	13	change_technology
51	Can delete technology	13	delete_technology
52	Can view technology	13	view_technology
53	Can add offer technology	14	add_offertechnology
54	Can change offer technology	14	change_offertechnology
55	Can delete offer technology	14	delete_offertechnology
56	Can view offer technology	14	view_offertechnology
57	Can add blacklisted token	15	add_blacklistedtoken
58	Can change blacklisted token	15	change_blacklistedtoken
59	Can delete blacklisted token	15	delete_blacklistedtoken
60	Can view blacklisted token	15	view_blacklistedtoken
61	Can add outstanding token	16	add_outstandingtoken
62	Can change outstanding token	16	change_outstandingtoken
63	Can delete outstanding token	16	delete_outstandingtoken
64	Can view outstanding token	16	view_outstandingtoken
\.


--
-- Data for Name: candidates; Type: TABLE DATA; Schema: public; Owner: luisg
--

COPY public.candidates (id, description, seniority, experience_years, status, created, modified, creator_id, modifier_id, user_id) FROM stdin;
b010f66b-a4d2-4c7a-9364-46c8ac980d4c	Desarrollador frontend con experiencia en React y Astro	trainee	1	t	2026-06-30 14:00:48.191918+00	2026-06-30 14:00:48.191933+00	62826344-37f2-4166-b8cb-ec428b49c131	62826344-37f2-4166-b8cb-ec428b49c131	62826344-37f2-4166-b8cb-ec428b49c131
bef535f0-281a-493f-aade-ae4d8625f60e	Desarrollador fullstack	senior	10	t	2026-06-30 15:53:47.760537+00	2026-06-30 15:53:47.760548+00	91300142-f861-40ff-8910-e413ed0c6b57	91300142-f861-40ff-8910-e413ed0c6b57	91300142-f861-40ff-8910-e413ed0c6b57
\.


--
-- Data for Name: companies; Type: TABLE DATA; Schema: public; Owner: luisg
--

COPY public.companies (id, name, status, created, modified, creator_id, modifier_id) FROM stdin;
e23536a9-2d96-4e5d-b3af-f1dde10bd5ff	GLOBANT	t	2026-06-30 04:16:04.449274+00	2026-06-30 04:16:04.449284+00	b2a7abf6-66a3-4559-9f79-32a7b071aa39	b2a7abf6-66a3-4559-9f79-32a7b071aa39
90efd7e9-0c81-469c-8641-79379d1de664	MERCADO LIBRE	t	2026-06-30 04:16:04.450243+00	2026-06-30 04:16:04.45025+00	b2a7abf6-66a3-4559-9f79-32a7b071aa39	b2a7abf6-66a3-4559-9f79-32a7b071aa39
92a1e2f6-28fc-4ea8-a650-203155fb118c	RAPPI	t	2026-06-30 04:16:04.451006+00	2026-06-30 04:16:04.451013+00	b2a7abf6-66a3-4559-9f79-32a7b071aa39	b2a7abf6-66a3-4559-9f79-32a7b071aa39
23d15f26-87bf-491e-a725-985ead5e30e4	NTT DATA	t	2026-06-30 04:16:04.451821+00	2026-06-30 04:16:04.451828+00	b2a7abf6-66a3-4559-9f79-32a7b071aa39	b2a7abf6-66a3-4559-9f79-32a7b071aa39
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: luisg
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: luisg
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	contenttypes	contenttype
5	sessions	session
6	jobs	user
7	jobs	candidate
8	jobs	company
9	jobs	location
10	jobs	offer
11	jobs	application
12	jobs	recruiter
13	jobs	technology
14	jobs	offertechnology
15	token_blacklist	blacklistedtoken
16	token_blacklist	outstandingtoken
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: luisg
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-06-30 04:15:46.402778+00
2	contenttypes	0002_remove_content_type_name	2026-06-30 04:15:46.405997+00
3	auth	0001_initial	2026-06-30 04:15:46.425242+00
4	auth	0002_alter_permission_name_max_length	2026-06-30 04:15:46.427485+00
5	auth	0003_alter_user_email_max_length	2026-06-30 04:15:46.430188+00
6	auth	0004_alter_user_username_opts	2026-06-30 04:15:46.43268+00
7	auth	0005_alter_user_last_login_null	2026-06-30 04:15:46.435225+00
8	auth	0006_require_contenttypes_0002	2026-06-30 04:15:46.436189+00
9	auth	0007_alter_validators_add_error_messages	2026-06-30 04:15:46.438858+00
10	auth	0008_alter_user_username_max_length	2026-06-30 04:15:46.441631+00
11	auth	0009_alter_user_last_name_max_length	2026-06-30 04:15:46.444358+00
12	auth	0010_alter_group_name_max_length	2026-06-30 04:15:46.447369+00
13	auth	0011_update_proxy_permissions	2026-06-30 04:15:46.450185+00
14	auth	0012_alter_user_first_name_max_length	2026-06-30 04:15:46.453381+00
15	jobs	0001_initial	2026-06-30 04:15:46.575089+00
16	admin	0001_initial	2026-06-30 04:15:46.588255+00
17	admin	0002_logentry_remove_auto_add	2026-06-30 04:15:46.594684+00
18	admin	0003_logentry_add_action_flag_choices	2026-06-30 04:15:46.601135+00
19	sessions	0001_initial	2026-06-30 04:15:46.607203+00
20	token_blacklist	0001_initial	2026-06-30 04:15:46.628653+00
21	token_blacklist	0002_outstandingtoken_jti_hex	2026-06-30 04:15:46.635585+00
22	token_blacklist	0003_auto_20171017_2007	2026-06-30 04:15:46.644156+00
23	token_blacklist	0004_auto_20171017_2013	2026-06-30 04:15:46.65475+00
24	token_blacklist	0005_remove_outstandingtoken_jti	2026-06-30 04:15:46.66223+00
25	token_blacklist	0006_auto_20171017_2113	2026-06-30 04:15:46.669958+00
26	token_blacklist	0007_auto_20171017_2214	2026-06-30 04:15:46.702698+00
27	token_blacklist	0008_migrate_to_bigautofield	2026-06-30 04:15:46.726629+00
28	token_blacklist	0010_fix_migrate_to_bigautofield	2026-06-30 04:15:46.736512+00
29	token_blacklist	0011_linearizes_history	2026-06-30 04:15:46.73758+00
30	token_blacklist	0012_alter_outstandingtoken_user	2026-06-30 04:15:46.744321+00
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: luisg
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
\.


--
-- Data for Name: locations; Type: TABLE DATA; Schema: public; Owner: luisg
--

COPY public.locations (id, name, status, created, modified, creator_id, modifier_id) FROM stdin;
1a6df52c-e33a-43ca-8539-43810f28293a	LIMA, PERÚ	t	2026-06-30 04:16:04.452775+00	2026-06-30 04:16:04.452782+00	b2a7abf6-66a3-4559-9f79-32a7b071aa39	b2a7abf6-66a3-4559-9f79-32a7b071aa39
7eaa2e19-9f58-445e-916a-fae402d3a80e	BUENOS AIRES, ARGENTINA	t	2026-06-30 04:16:04.453841+00	2026-06-30 04:16:04.453849+00	b2a7abf6-66a3-4559-9f79-32a7b071aa39	b2a7abf6-66a3-4559-9f79-32a7b071aa39
f1da18f9-2097-4376-adc8-ceeb15b323c4	BOGOTÁ, COLOMBIA	t	2026-06-30 04:16:04.454624+00	2026-06-30 04:16:04.454631+00	b2a7abf6-66a3-4559-9f79-32a7b071aa39	b2a7abf6-66a3-4559-9f79-32a7b071aa39
\.


--
-- Data for Name: offers; Type: TABLE DATA; Schema: public; Owner: luisg
--

COPY public.offers (id, title, description, modality, seniority, status, salary, created, modified, creator_id, location_id, modifier_id, recruiter_id) FROM stdin;
a2619fdb-6161-4639-96d0-44f98f56dcc7	BACKEND DEVELOPER PYTHON	Buscamos desarrollador backend con experiencia en Django y APIs REST	remote	mid	t	3500.00	2026-06-30 15:36:56.339936+00	2026-06-30 15:36:56.339948+00	b7ae581b-2e5a-4638-906f-2bc4f115dcde	1a6df52c-e33a-43ca-8539-43810f28293a	b7ae581b-2e5a-4638-906f-2bc4f115dcde	7d6bc49b-247a-4869-a214-0b5072adf16d
6764f58b-15f3-4cfe-b8db-a6ec05165a9f	FRONTEND DEVELOPER REACT	Buscamos desarrollador frontend con experiencia en React y TypeScript	hybrid	senior	t	4200.00	2026-06-30 15:42:23.586477+00	2026-06-30 15:42:23.586486+00	b7ae581b-2e5a-4638-906f-2bc4f115dcde	7eaa2e19-9f58-445e-916a-fae402d3a80e	b7ae581b-2e5a-4638-906f-2bc4f115dcde	7d6bc49b-247a-4869-a214-0b5072adf16d
b4f20ed9-125f-4799-91f2-df44d8174c2d	FULLSTACK DEVELOPER	Buscamos desarrollador fullstack con experiencia en Django, React y PostgreSQL	presential	lead	t	5500.00	2026-06-30 15:50:15.356227+00	2026-06-30 15:50:15.356238+00	b92c4cc7-be25-400f-bd96-d60ab1e8c187	f1da18f9-2097-4376-adc8-ceeb15b323c4	b92c4cc7-be25-400f-bd96-d60ab1e8c187	17981f25-e115-4525-99ee-376142ae4253
\.


--
-- Data for Name: offers_technologies; Type: TABLE DATA; Schema: public; Owner: luisg
--

COPY public.offers_technologies (id, offer_id, technology_id) FROM stdin;
6e4c1707-4d56-4e87-8c0d-aae743c61e47	a2619fdb-6161-4639-96d0-44f98f56dcc7	49554bf9-70fd-4b4d-8fea-ecb4c32b0ea2
10a08edc-c23d-49fe-b175-5b5ce69f1146	a2619fdb-6161-4639-96d0-44f98f56dcc7	355858bf-a862-463f-a29d-90b54e39b33f
fb887dd4-64bd-4394-9a7b-04a9d7f43fe0	6764f58b-15f3-4cfe-b8db-a6ec05165a9f	78395a84-20b5-490d-9b94-8518a2caac26
af2be9cc-5f72-4a45-80a1-931cbc11ddaa	6764f58b-15f3-4cfe-b8db-a6ec05165a9f	173ac8a8-b787-42f7-837c-a72c435b4f9f
f1dd258d-99e6-4755-abb9-21caf06c3da9	b4f20ed9-125f-4799-91f2-df44d8174c2d	49554bf9-70fd-4b4d-8fea-ecb4c32b0ea2
3e583dc1-205c-48ad-a6de-210ae12d005f	b4f20ed9-125f-4799-91f2-df44d8174c2d	16988627-ae7e-45a4-a8c6-f0ef1e022048
bb4202db-580f-4108-96e7-8ed7becb21d5	b4f20ed9-125f-4799-91f2-df44d8174c2d	78395a84-20b5-490d-9b94-8518a2caac26
\.


--
-- Data for Name: recruiters; Type: TABLE DATA; Schema: public; Owner: luisg
--

COPY public.recruiters (id, description, contact_email, status, created, modified, company_id, creator_id, modifier_id, user_id) FROM stdin;
7d6bc49b-247a-4869-a214-0b5072adf16d	Reclutadora con años de experiencia	lucia_apaza@gmail.com	t	2026-06-30 14:06:15.471636+00	2026-06-30 14:06:15.471647+00	92a1e2f6-28fc-4ea8-a650-203155fb118c	b7ae581b-2e5a-4638-906f-2bc4f115dcde	b7ae581b-2e5a-4638-906f-2bc4f115dcde	b7ae581b-2e5a-4638-906f-2bc4f115dcde
17981f25-e115-4525-99ee-376142ae4253	Reclutador poco experimentado	maria_rodriguez@gmail.com	t	2026-06-30 15:48:22.778558+00	2026-06-30 15:48:22.778568+00	23d15f26-87bf-491e-a725-985ead5e30e4	b92c4cc7-be25-400f-bd96-d60ab1e8c187	b92c4cc7-be25-400f-bd96-d60ab1e8c187	b92c4cc7-be25-400f-bd96-d60ab1e8c187
\.


--
-- Data for Name: technologies; Type: TABLE DATA; Schema: public; Owner: luisg
--

COPY public.technologies (id, name, status, created, modified, creator_id, modifier_id) FROM stdin;
355858bf-a862-463f-a29d-90b54e39b33f	PYTHON	t	2026-06-30 04:16:04.455573+00	2026-06-30 04:16:04.45558+00	b2a7abf6-66a3-4559-9f79-32a7b071aa39	b2a7abf6-66a3-4559-9f79-32a7b071aa39
49554bf9-70fd-4b4d-8fea-ecb4c32b0ea2	DJANGO	t	2026-06-30 04:16:04.456489+00	2026-06-30 04:16:04.456495+00	b2a7abf6-66a3-4559-9f79-32a7b071aa39	b2a7abf6-66a3-4559-9f79-32a7b071aa39
78395a84-20b5-490d-9b94-8518a2caac26	REACT	t	2026-06-30 04:16:04.457242+00	2026-06-30 04:16:04.457249+00	b2a7abf6-66a3-4559-9f79-32a7b071aa39	b2a7abf6-66a3-4559-9f79-32a7b071aa39
173ac8a8-b787-42f7-837c-a72c435b4f9f	TYPESCRIPT	t	2026-06-30 04:16:04.458011+00	2026-06-30 04:16:04.458017+00	b2a7abf6-66a3-4559-9f79-32a7b071aa39	b2a7abf6-66a3-4559-9f79-32a7b071aa39
16988627-ae7e-45a4-a8c6-f0ef1e022048	POSTGRESQL	t	2026-06-30 04:16:04.458763+00	2026-06-30 04:16:04.45877+00	b2a7abf6-66a3-4559-9f79-32a7b071aa39	b2a7abf6-66a3-4559-9f79-32a7b071aa39
\.


--
-- Data for Name: token_blacklist_blacklistedtoken; Type: TABLE DATA; Schema: public; Owner: luisg
--

COPY public.token_blacklist_blacklistedtoken (id, blacklisted_at, token_id) FROM stdin;
1	2026-06-30 15:18:46.116984+00	3
\.


--
-- Data for Name: token_blacklist_outstandingtoken; Type: TABLE DATA; Schema: public; Owner: luisg
--

COPY public.token_blacklist_outstandingtoken (id, token, created_at, expires_at, user_id, jti) FROM stdin;
1	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4MjkxMzc5NiwiaWF0IjoxNzgyODI3Mzk2LCJqdGkiOiJiOWZhMDExYWQzMzM0NzQxYjNlOTI2Y2U1NWY4ZjJjNSIsInVzZXJfaWQiOiI2MjgyNjM0NC0zN2YyLTQxNjYtYjhjYi1lYzQyOGI0OWMxMzEifQ.LSyzWBlZRL7UqF27rGb5M3MYUbb11cXJCOjPZv2LgDE	2026-06-30 13:49:56.482281+00	2026-07-01 13:49:56+00	62826344-37f2-4166-b8cb-ec428b49c131	b9fa011ad3334741b3e926ce55f8f2c5
2	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4MzQzMjc4MywiaWF0IjoxNzgyODI3OTgzLCJqdGkiOiJkNDliYzQwMGVjZjA0M2Q5YmVhZTljMGQ2OGVjYjlkMyIsInVzZXJfaWQiOiI2MjgyNjM0NC0zN2YyLTQxNjYtYjhjYi1lYzQyOGI0OWMxMzEifQ.ztOpOwzqr4dBlhdeTKbx_gnRIQ6huXjUC7uzlyOkA0A	2026-06-30 13:59:43.689826+00	2026-07-07 13:59:43+00	62826344-37f2-4166-b8cb-ec428b49c131	d49bc400ecf043d9beae9c0d68ecb9d3
3	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4MzQzMzA4OCwiaWF0IjoxNzgyODI4Mjg4LCJqdGkiOiJlYWE3MDdkMWVkZmI0OGMxOGVlYWYzMmY0NTc0YWZjNCIsInVzZXJfaWQiOiJiN2FlNTgxYi0yZTVhLTQ2MzgtOTA2Zi0yYmM0ZjExNWRjZGUifQ.lXXmrvRTGP66OR4nMNtjXyhAwRwZSwCSYydMxN7HefM	2026-06-30 14:04:48.135168+00	2026-07-07 14:04:48+00	b7ae581b-2e5a-4638-906f-2bc4f115dcde	eaa707d1edfb48c18eeaf32f4574afc4
4	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4MzQzODQ2NSwiaWF0IjoxNzgyODMzNjY1LCJqdGkiOiJhYzM4YmQ4ODU3Zjg0NWY4OWM5MTZlY2UzZjlmYjUzNCIsInVzZXJfaWQiOiJiN2FlNTgxYi0yZTVhLTQ2MzgtOTA2Zi0yYmM0ZjExNWRjZGUifQ.6RdvMYCW77V7tlNJ7Kg0Qb9iC-SwFSja5e1-snCPOnM	2026-06-30 15:34:25.92434+00	2026-07-07 15:34:25+00	b7ae581b-2e5a-4638-906f-2bc4f115dcde	ac38bd8857f845f89c916ece3f9fb534
5	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4MzQzOTIwNSwiaWF0IjoxNzgyODM0NDA1LCJqdGkiOiI0NDNhNDJmMTQxZTg0NThjODQ0NmNiMGI3ODUwZWE4NyIsInVzZXJfaWQiOiJiOTJjNGNjNy1iZTI1LTQwMGYtYmQ5Ni1kNjBhYjFlOGMxODcifQ.hPD-zrlLZ_Rq8dy0kLkBH8wCFsyePEsG8_M9qCeY_9c	2026-06-30 15:46:45.064373+00	2026-07-07 15:46:45+00	b92c4cc7-be25-400f-bd96-d60ab1e8c187	443a42f141e8458c8446cb0b7850ea87
6	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4MzQzOTU0NiwiaWF0IjoxNzgyODM0NzQ2LCJqdGkiOiJkMjVjZDRkMjk3NmQ0N2Q0YTBhYWMxMzIxNjE0NTE0NCIsInVzZXJfaWQiOiI5MTMwMDE0Mi1mODYxLTQwZmYtODkxMC1lNDEzZWQwYzZiNTcifQ.r0lP-KrytWVf9ktm2pAo3x-KBFN85665xU1zhi2hNgk	2026-06-30 15:52:26.519841+00	2026-07-07 15:52:26+00	91300142-f861-40ff-8910-e413ed0c6b57	d25cd4d2976d47d4a0aac13216145144
7	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4MzQzOTk5NSwiaWF0IjoxNzgyODM1MTk1LCJqdGkiOiIzMTRkMDg1OTY4M2Q0MmViYjcxNGQyMmQ3ZjI2ODg5YyIsInVzZXJfaWQiOiI2MjgyNjM0NC0zN2YyLTQxNjYtYjhjYi1lYzQyOGI0OWMxMzEifQ.1LBDD0jTimkzYdsTvfiWog-O_DSXv2J2rH3wtvVDIjI	2026-06-30 15:59:55.907402+00	2026-07-07 15:59:55+00	62826344-37f2-4166-b8cb-ec428b49c131	314d0859683d42ebb714d22d7f26889c
8	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4MzQ0MDEyMywiaWF0IjoxNzgyODM1MzIzLCJqdGkiOiIwMTM4NGIyYThkOGU0NmMyOWViNGU2OTBkYzc4M2ExYiIsInVzZXJfaWQiOiJiN2FlNTgxYi0yZTVhLTQ2MzgtOTA2Zi0yYmM0ZjExNWRjZGUifQ.A-LBTOguSsrZul-vk6wW0Mm5qVO5pwKzTzYExd96skM	2026-06-30 16:02:03.569714+00	2026-07-07 16:02:03+00	b7ae581b-2e5a-4638-906f-2bc4f115dcde	01384b2a8d8e46c29eb4e690dc783a1b
9	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4MzQ4Mzg2MSwiaWF0IjoxNzgyODc5MDYxLCJqdGkiOiJkMjM1ZjU0ZWU2MTc0OTA2YjkzMDU3MWMyOTU0MGQ2ZSIsInVzZXJfaWQiOiJiOTJjNGNjNy1iZTI1LTQwMGYtYmQ5Ni1kNjBhYjFlOGMxODcifQ.6lNOwumEZ44lIjyTdIBpJLagg8vH0M9lu4GMkSv0vGs	2026-07-01 04:11:01.651012+00	2026-07-08 04:11:01+00	b92c4cc7-be25-400f-bd96-d60ab1e8c187	d235f54ee6174906b930571c29540d6e
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: luisg
--

COPY public.users (password, last_login, is_superuser, username, email, is_staff, is_active, date_joined, first_name, last_name, id, modified, creator_id, modifier_id) FROM stdin;
pbkdf2_sha256$1000000$TUVr6BszshgWnRxokBcfhG$dgpA2cVaYD5vnQnJgfQyjX2fWBgCReWjeq8cZlnMW9I=	\N	t	luisg	luisgardaz13@gmail.com	t	t	2026-06-30 04:16:04.320959+00			b2a7abf6-66a3-4559-9f79-32a7b071aa39	2026-06-30 04:16:04.442979+00	b2a7abf6-66a3-4559-9f79-32a7b071aa39	b2a7abf6-66a3-4559-9f79-32a7b071aa39
pbkdf2_sha256$1000000$X85lQ1hnOpKVGULpXwT3ck$c68tvEgBU/li9G89WXp/9Nk97C7Y5WLYfHGznz7/BOs=	\N	f	jose_gimenez	jose@gmail.com	f	t	2026-06-30 13:48:18.699982+00	JOSE	GIMENEZ	62826344-37f2-4166-b8cb-ec428b49c131	2026-06-30 13:48:18.829908+00	62826344-37f2-4166-b8cb-ec428b49c131	62826344-37f2-4166-b8cb-ec428b49c131
pbkdf2_sha256$1000000$3j4XPoXb7JsqNQrzmOMNRf$IT1Y86n+FsLrlkB39B0QbZgvMaKbM6cpmfKGfM7bovw=	\N	f	lucia_apaza	lucia@gmail.com	f	t	2026-06-30 14:04:14.152587+00	LUCIA	APAZA	b7ae581b-2e5a-4638-906f-2bc4f115dcde	2026-06-30 14:04:14.282482+00	b7ae581b-2e5a-4638-906f-2bc4f115dcde	b7ae581b-2e5a-4638-906f-2bc4f115dcde
pbkdf2_sha256$1000000$4iGZWee8351R7xz1K52lqE$8QZeIToETLQm+ZnKTi8KdofvGsZU+VCJ6bU72MIAkAo=	\N	f	maria_rodriguez	maria@gmail.com	f	t	2026-06-30 15:46:20.26775+00	MARIA	RODRIGUEZ	b92c4cc7-be25-400f-bd96-d60ab1e8c187	2026-06-30 15:46:20.401068+00	b92c4cc7-be25-400f-bd96-d60ab1e8c187	b92c4cc7-be25-400f-bd96-d60ab1e8c187
pbkdf2_sha256$1000000$ht1TN2T9hAsfhjT81BWi3O$0sqqAlf28Ij4dXPq4v+49I/MLSXCVO7lq4QriFhjDWo=	\N	f	carlos_perez	carlos@gmail.com	f	t	2026-06-30 15:51:56.190257+00	CARLOS	PEREZ	91300142-f861-40ff-8910-e413ed0c6b57	2026-06-30 15:51:56.332059+00	91300142-f861-40ff-8910-e413ed0c6b57	91300142-f861-40ff-8910-e413ed0c6b57
\.


--
-- Data for Name: users_groups; Type: TABLE DATA; Schema: public; Owner: luisg
--

COPY public.users_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: users_user_permissions; Type: TABLE DATA; Schema: public; Owner: luisg
--

COPY public.users_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: luisg
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: luisg
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: luisg
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 64, true);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: luisg
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, false);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: luisg
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 16, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: luisg
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 30, true);


--
-- Name: token_blacklist_blacklistedtoken_id_seq; Type: SEQUENCE SET; Schema: public; Owner: luisg
--

SELECT pg_catalog.setval('public.token_blacklist_blacklistedtoken_id_seq', 1, true);


--
-- Name: token_blacklist_outstandingtoken_id_seq; Type: SEQUENCE SET; Schema: public; Owner: luisg
--

SELECT pg_catalog.setval('public.token_blacklist_outstandingtoken_id_seq', 9, true);


--
-- Name: users_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: luisg
--

SELECT pg_catalog.setval('public.users_groups_id_seq', 1, false);


--
-- Name: users_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: luisg
--

SELECT pg_catalog.setval('public.users_user_permissions_id_seq', 1, false);


--
-- Name: applications applications_pkey; Type: CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.applications
    ADD CONSTRAINT applications_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: candidates candidates_pkey; Type: CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.candidates
    ADD CONSTRAINT candidates_pkey PRIMARY KEY (id);


--
-- Name: candidates candidates_user_id_key; Type: CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.candidates
    ADD CONSTRAINT candidates_user_id_key UNIQUE (user_id);


--
-- Name: companies companies_pkey; Type: CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.companies
    ADD CONSTRAINT companies_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: locations locations_name_key; Type: CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.locations
    ADD CONSTRAINT locations_name_key UNIQUE (name);


--
-- Name: locations locations_pkey; Type: CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.locations
    ADD CONSTRAINT locations_pkey PRIMARY KEY (id);


--
-- Name: offers offers_pkey; Type: CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.offers
    ADD CONSTRAINT offers_pkey PRIMARY KEY (id);


--
-- Name: offers_technologies offers_technologies_pkey; Type: CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.offers_technologies
    ADD CONSTRAINT offers_technologies_pkey PRIMARY KEY (id);


--
-- Name: recruiters recruiters_pkey; Type: CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.recruiters
    ADD CONSTRAINT recruiters_pkey PRIMARY KEY (id);


--
-- Name: recruiters recruiters_user_id_key; Type: CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.recruiters
    ADD CONSTRAINT recruiters_user_id_key UNIQUE (user_id);


--
-- Name: technologies technologies_name_key; Type: CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.technologies
    ADD CONSTRAINT technologies_name_key UNIQUE (name);


--
-- Name: technologies technologies_pkey; Type: CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.technologies
    ADD CONSTRAINT technologies_pkey PRIMARY KEY (id);


--
-- Name: token_blacklist_blacklistedtoken token_blacklist_blacklistedtoken_pkey; Type: CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.token_blacklist_blacklistedtoken
    ADD CONSTRAINT token_blacklist_blacklistedtoken_pkey PRIMARY KEY (id);


--
-- Name: token_blacklist_blacklistedtoken token_blacklist_blacklistedtoken_token_id_key; Type: CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.token_blacklist_blacklistedtoken
    ADD CONSTRAINT token_blacklist_blacklistedtoken_token_id_key UNIQUE (token_id);


--
-- Name: token_blacklist_outstandingtoken token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_uniq; Type: CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.token_blacklist_outstandingtoken
    ADD CONSTRAINT token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_uniq UNIQUE (jti);


--
-- Name: token_blacklist_outstandingtoken token_blacklist_outstandingtoken_pkey; Type: CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.token_blacklist_outstandingtoken
    ADD CONSTRAINT token_blacklist_outstandingtoken_pkey PRIMARY KEY (id);


--
-- Name: users_groups users_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.users_groups
    ADD CONSTRAINT users_groups_pkey PRIMARY KEY (id);


--
-- Name: users_groups users_groups_user_id_group_id_fc7788e8_uniq; Type: CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.users_groups
    ADD CONSTRAINT users_groups_user_id_group_id_fc7788e8_uniq UNIQUE (user_id, group_id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: users_user_permissions users_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.users_user_permissions
    ADD CONSTRAINT users_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: users_user_permissions users_user_permissions_user_id_permission_id_3b86cbdf_uniq; Type: CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.users_user_permissions
    ADD CONSTRAINT users_user_permissions_user_id_permission_id_3b86cbdf_uniq UNIQUE (user_id, permission_id);


--
-- Name: users users_username_key; Type: CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_username_key UNIQUE (username);


--
-- Name: applications_candidate_id_f90db3c6; Type: INDEX; Schema: public; Owner: luisg
--

CREATE INDEX applications_candidate_id_f90db3c6 ON public.applications USING btree (candidate_id);


--
-- Name: applications_creator_id_686cec4b; Type: INDEX; Schema: public; Owner: luisg
--

CREATE INDEX applications_creator_id_686cec4b ON public.applications USING btree (creator_id);


--
-- Name: applications_modifier_id_2b36e80e; Type: INDEX; Schema: public; Owner: luisg
--

CREATE INDEX applications_modifier_id_2b36e80e ON public.applications USING btree (modifier_id);


--
-- Name: applications_offer_id_82d40565; Type: INDEX; Schema: public; Owner: luisg
--

CREATE INDEX applications_offer_id_82d40565 ON public.applications USING btree (offer_id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: luisg
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: luisg
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: luisg
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: luisg
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: candidates_creator_id_de0c3f46; Type: INDEX; Schema: public; Owner: luisg
--

CREATE INDEX candidates_creator_id_de0c3f46 ON public.candidates USING btree (creator_id);


--
-- Name: candidates_modifier_id_16ff9fb3; Type: INDEX; Schema: public; Owner: luisg
--

CREATE INDEX candidates_modifier_id_16ff9fb3 ON public.candidates USING btree (modifier_id);


--
-- Name: companies_creator_id_458fd19b; Type: INDEX; Schema: public; Owner: luisg
--

CREATE INDEX companies_creator_id_458fd19b ON public.companies USING btree (creator_id);


--
-- Name: companies_modifier_id_4fed516d; Type: INDEX; Schema: public; Owner: luisg
--

CREATE INDEX companies_modifier_id_4fed516d ON public.companies USING btree (modifier_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: luisg
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: luisg
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: luisg
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: luisg
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: idx_user_full_name; Type: INDEX; Schema: public; Owner: luisg
--

CREATE INDEX idx_user_full_name ON public.users USING btree (first_name, last_name);


--
-- Name: locations_creator_id_8874d202; Type: INDEX; Schema: public; Owner: luisg
--

CREATE INDEX locations_creator_id_8874d202 ON public.locations USING btree (creator_id);


--
-- Name: locations_modifier_id_8af9e79a; Type: INDEX; Schema: public; Owner: luisg
--

CREATE INDEX locations_modifier_id_8af9e79a ON public.locations USING btree (modifier_id);


--
-- Name: locations_name_512a106e_like; Type: INDEX; Schema: public; Owner: luisg
--

CREATE INDEX locations_name_512a106e_like ON public.locations USING btree (name varchar_pattern_ops);


--
-- Name: offers_creator_id_9bf8c888; Type: INDEX; Schema: public; Owner: luisg
--

CREATE INDEX offers_creator_id_9bf8c888 ON public.offers USING btree (creator_id);


--
-- Name: offers_location_id_949e7bb5; Type: INDEX; Schema: public; Owner: luisg
--

CREATE INDEX offers_location_id_949e7bb5 ON public.offers USING btree (location_id);


--
-- Name: offers_modifier_id_f0aa9d0f; Type: INDEX; Schema: public; Owner: luisg
--

CREATE INDEX offers_modifier_id_f0aa9d0f ON public.offers USING btree (modifier_id);


--
-- Name: offers_recruiter_id_73e30ceb; Type: INDEX; Schema: public; Owner: luisg
--

CREATE INDEX offers_recruiter_id_73e30ceb ON public.offers USING btree (recruiter_id);


--
-- Name: offers_technologies_offer_id_b96d39e9; Type: INDEX; Schema: public; Owner: luisg
--

CREATE INDEX offers_technologies_offer_id_b96d39e9 ON public.offers_technologies USING btree (offer_id);


--
-- Name: offers_technologies_technology_id_9bb12fae; Type: INDEX; Schema: public; Owner: luisg
--

CREATE INDEX offers_technologies_technology_id_9bb12fae ON public.offers_technologies USING btree (technology_id);


--
-- Name: recruiters_company_id_4654a403; Type: INDEX; Schema: public; Owner: luisg
--

CREATE INDEX recruiters_company_id_4654a403 ON public.recruiters USING btree (company_id);


--
-- Name: recruiters_creator_id_e98d4e08; Type: INDEX; Schema: public; Owner: luisg
--

CREATE INDEX recruiters_creator_id_e98d4e08 ON public.recruiters USING btree (creator_id);


--
-- Name: recruiters_modifier_id_b4be1559; Type: INDEX; Schema: public; Owner: luisg
--

CREATE INDEX recruiters_modifier_id_b4be1559 ON public.recruiters USING btree (modifier_id);


--
-- Name: technologies_creator_id_ae983019; Type: INDEX; Schema: public; Owner: luisg
--

CREATE INDEX technologies_creator_id_ae983019 ON public.technologies USING btree (creator_id);


--
-- Name: technologies_modifier_id_b92b78af; Type: INDEX; Schema: public; Owner: luisg
--

CREATE INDEX technologies_modifier_id_b92b78af ON public.technologies USING btree (modifier_id);


--
-- Name: technologies_name_21c5c2f9_like; Type: INDEX; Schema: public; Owner: luisg
--

CREATE INDEX technologies_name_21c5c2f9_like ON public.technologies USING btree (name varchar_pattern_ops);


--
-- Name: token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_like; Type: INDEX; Schema: public; Owner: luisg
--

CREATE INDEX token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_like ON public.token_blacklist_outstandingtoken USING btree (jti varchar_pattern_ops);


--
-- Name: token_blacklist_outstandingtoken_user_id_83bc629a; Type: INDEX; Schema: public; Owner: luisg
--

CREATE INDEX token_blacklist_outstandingtoken_user_id_83bc629a ON public.token_blacklist_outstandingtoken USING btree (user_id);


--
-- Name: users_creator_id_05421e81; Type: INDEX; Schema: public; Owner: luisg
--

CREATE INDEX users_creator_id_05421e81 ON public.users USING btree (creator_id);


--
-- Name: users_groups_group_id_2f3517aa; Type: INDEX; Schema: public; Owner: luisg
--

CREATE INDEX users_groups_group_id_2f3517aa ON public.users_groups USING btree (group_id);


--
-- Name: users_groups_user_id_f500bee5; Type: INDEX; Schema: public; Owner: luisg
--

CREATE INDEX users_groups_user_id_f500bee5 ON public.users_groups USING btree (user_id);


--
-- Name: users_modifier_id_60df99e1; Type: INDEX; Schema: public; Owner: luisg
--

CREATE INDEX users_modifier_id_60df99e1 ON public.users USING btree (modifier_id);


--
-- Name: users_user_permissions_permission_id_6d08dcd2; Type: INDEX; Schema: public; Owner: luisg
--

CREATE INDEX users_user_permissions_permission_id_6d08dcd2 ON public.users_user_permissions USING btree (permission_id);


--
-- Name: users_user_permissions_user_id_92473840; Type: INDEX; Schema: public; Owner: luisg
--

CREATE INDEX users_user_permissions_user_id_92473840 ON public.users_user_permissions USING btree (user_id);


--
-- Name: users_username_e8658fc8_like; Type: INDEX; Schema: public; Owner: luisg
--

CREATE INDEX users_username_e8658fc8_like ON public.users USING btree (username varchar_pattern_ops);


--
-- Name: applications applications_candidate_id_f90db3c6_fk_candidates_id; Type: FK CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.applications
    ADD CONSTRAINT applications_candidate_id_f90db3c6_fk_candidates_id FOREIGN KEY (candidate_id) REFERENCES public.candidates(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: applications applications_creator_id_686cec4b_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.applications
    ADD CONSTRAINT applications_creator_id_686cec4b_fk_users_id FOREIGN KEY (creator_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: applications applications_modifier_id_2b36e80e_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.applications
    ADD CONSTRAINT applications_modifier_id_2b36e80e_fk_users_id FOREIGN KEY (modifier_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: applications applications_offer_id_82d40565_fk_offers_id; Type: FK CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.applications
    ADD CONSTRAINT applications_offer_id_82d40565_fk_offers_id FOREIGN KEY (offer_id) REFERENCES public.offers(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: candidates candidates_creator_id_de0c3f46_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.candidates
    ADD CONSTRAINT candidates_creator_id_de0c3f46_fk_users_id FOREIGN KEY (creator_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: candidates candidates_modifier_id_16ff9fb3_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.candidates
    ADD CONSTRAINT candidates_modifier_id_16ff9fb3_fk_users_id FOREIGN KEY (modifier_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: candidates candidates_user_id_38b3e027_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.candidates
    ADD CONSTRAINT candidates_user_id_38b3e027_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: companies companies_creator_id_458fd19b_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.companies
    ADD CONSTRAINT companies_creator_id_458fd19b_fk_users_id FOREIGN KEY (creator_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: companies companies_modifier_id_4fed516d_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.companies
    ADD CONSTRAINT companies_modifier_id_4fed516d_fk_users_id FOREIGN KEY (modifier_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: locations locations_creator_id_8874d202_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.locations
    ADD CONSTRAINT locations_creator_id_8874d202_fk_users_id FOREIGN KEY (creator_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: locations locations_modifier_id_8af9e79a_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.locations
    ADD CONSTRAINT locations_modifier_id_8af9e79a_fk_users_id FOREIGN KEY (modifier_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: offers offers_creator_id_9bf8c888_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.offers
    ADD CONSTRAINT offers_creator_id_9bf8c888_fk_users_id FOREIGN KEY (creator_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: offers offers_location_id_949e7bb5_fk_locations_id; Type: FK CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.offers
    ADD CONSTRAINT offers_location_id_949e7bb5_fk_locations_id FOREIGN KEY (location_id) REFERENCES public.locations(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: offers offers_modifier_id_f0aa9d0f_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.offers
    ADD CONSTRAINT offers_modifier_id_f0aa9d0f_fk_users_id FOREIGN KEY (modifier_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: offers offers_recruiter_id_73e30ceb_fk_recruiters_id; Type: FK CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.offers
    ADD CONSTRAINT offers_recruiter_id_73e30ceb_fk_recruiters_id FOREIGN KEY (recruiter_id) REFERENCES public.recruiters(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: offers_technologies offers_technologies_offer_id_b96d39e9_fk_offers_id; Type: FK CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.offers_technologies
    ADD CONSTRAINT offers_technologies_offer_id_b96d39e9_fk_offers_id FOREIGN KEY (offer_id) REFERENCES public.offers(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: offers_technologies offers_technologies_technology_id_9bb12fae_fk_technologies_id; Type: FK CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.offers_technologies
    ADD CONSTRAINT offers_technologies_technology_id_9bb12fae_fk_technologies_id FOREIGN KEY (technology_id) REFERENCES public.technologies(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: recruiters recruiters_company_id_4654a403_fk_companies_id; Type: FK CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.recruiters
    ADD CONSTRAINT recruiters_company_id_4654a403_fk_companies_id FOREIGN KEY (company_id) REFERENCES public.companies(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: recruiters recruiters_creator_id_e98d4e08_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.recruiters
    ADD CONSTRAINT recruiters_creator_id_e98d4e08_fk_users_id FOREIGN KEY (creator_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: recruiters recruiters_modifier_id_b4be1559_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.recruiters
    ADD CONSTRAINT recruiters_modifier_id_b4be1559_fk_users_id FOREIGN KEY (modifier_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: recruiters recruiters_user_id_50c8b723_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.recruiters
    ADD CONSTRAINT recruiters_user_id_50c8b723_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: technologies technologies_creator_id_ae983019_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.technologies
    ADD CONSTRAINT technologies_creator_id_ae983019_fk_users_id FOREIGN KEY (creator_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: technologies technologies_modifier_id_b92b78af_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.technologies
    ADD CONSTRAINT technologies_modifier_id_b92b78af_fk_users_id FOREIGN KEY (modifier_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: token_blacklist_blacklistedtoken token_blacklist_blacklistedtoken_token_id_3cc7fe56_fk; Type: FK CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.token_blacklist_blacklistedtoken
    ADD CONSTRAINT token_blacklist_blacklistedtoken_token_id_3cc7fe56_fk FOREIGN KEY (token_id) REFERENCES public.token_blacklist_outstandingtoken(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: token_blacklist_outstandingtoken token_blacklist_outstandingtoken_user_id_83bc629a_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.token_blacklist_outstandingtoken
    ADD CONSTRAINT token_blacklist_outstandingtoken_user_id_83bc629a_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users users_creator_id_05421e81_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_creator_id_05421e81_fk_users_id FOREIGN KEY (creator_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_groups users_groups_group_id_2f3517aa_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.users_groups
    ADD CONSTRAINT users_groups_group_id_2f3517aa_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_groups users_groups_user_id_f500bee5_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.users_groups
    ADD CONSTRAINT users_groups_user_id_f500bee5_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users users_modifier_id_60df99e1_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_modifier_id_60df99e1_fk_users_id FOREIGN KEY (modifier_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_permissions users_user_permissio_permission_id_6d08dcd2_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.users_user_permissions
    ADD CONSTRAINT users_user_permissio_permission_id_6d08dcd2_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_permissions users_user_permissions_user_id_92473840_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.users_user_permissions
    ADD CONSTRAINT users_user_permissions_user_id_92473840_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict qohQLkqyIv6itE424VhhsJ3hSRwUshrOyCcrFHUhrAtdvsosR9FM40Amlj8sL41

