--
-- PostgreSQL database dump
--

\restrict qjdbKeaICmRGaZAsm3nd8chQTELyU4VeSRemzUt0iLtZC3IoUtCMBoEOVXmJoOk

-- Dumped from database version 16.14 (Debian 16.14-1.pgdg13+1)
-- Dumped by pg_dump version 16.14 (Debian 16.14-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: applications; Type: TABLE; Schema: public; Owner: luisg
--

CREATE TABLE public.applications (
    id uuid NOT NULL,
    status character varying(8) NOT NULL,
    created timestamp with time zone NOT NULL,
    modified timestamp with time zone NOT NULL,
    creator_id uuid NOT NULL,
    modifier_id uuid,
    candidate_id uuid NOT NULL,
    offer_id uuid NOT NULL
);


ALTER TABLE public.applications OWNER TO luisg;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: luisg
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO luisg;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: luisg
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: luisg
--

CREATE TABLE public.auth_group_permissions (
    id integer NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO luisg;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: luisg
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: luisg
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO luisg;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: luisg
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: candidates; Type: TABLE; Schema: public; Owner: luisg
--

CREATE TABLE public.candidates (
    id uuid NOT NULL,
    description character varying(500),
    seniority character varying(7) NOT NULL,
    experience_years integer NOT NULL,
    status boolean NOT NULL,
    created timestamp with time zone NOT NULL,
    modified timestamp with time zone NOT NULL,
    creator_id uuid NOT NULL,
    modifier_id uuid NOT NULL,
    user_id uuid NOT NULL
);


ALTER TABLE public.candidates OWNER TO luisg;

--
-- Name: companies; Type: TABLE; Schema: public; Owner: luisg
--

CREATE TABLE public.companies (
    id uuid NOT NULL,
    name character varying(255) NOT NULL,
    status boolean NOT NULL,
    created timestamp with time zone NOT NULL,
    modified timestamp with time zone NOT NULL,
    creator_id uuid,
    modifier_id uuid
);


ALTER TABLE public.companies OWNER TO luisg;

--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: luisg
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id uuid NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO luisg;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: luisg
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: luisg
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO luisg;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: luisg
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: luisg
--

CREATE TABLE public.django_migrations (
    id integer NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO luisg;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: luisg
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: luisg
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO luisg;

--
-- Name: locations; Type: TABLE; Schema: public; Owner: luisg
--

CREATE TABLE public.locations (
    id uuid NOT NULL,
    name character varying(100) NOT NULL,
    status boolean NOT NULL,
    created timestamp with time zone NOT NULL,
    modified timestamp with time zone NOT NULL,
    creator_id uuid,
    modifier_id uuid
);


ALTER TABLE public.locations OWNER TO luisg;

--
-- Name: offers; Type: TABLE; Schema: public; Owner: luisg
--

CREATE TABLE public.offers (
    id uuid NOT NULL,
    title character varying(255) NOT NULL,
    modality character varying(10) NOT NULL,
    seniority character varying(7) NOT NULL,
    status boolean NOT NULL,
    salary numeric(10,2),
    created timestamp with time zone NOT NULL,
    modified timestamp with time zone NOT NULL,
    creator_id uuid NOT NULL,
    location_id uuid NOT NULL,
    modifier_id uuid,
    recruiter_id uuid NOT NULL,
    description_detail character varying(2000) NOT NULL
);


ALTER TABLE public.offers OWNER TO luisg;

--
-- Name: offers_technologies; Type: TABLE; Schema: public; Owner: luisg
--

CREATE TABLE public.offers_technologies (
    id uuid NOT NULL,
    offer_id uuid NOT NULL,
    technology_id uuid NOT NULL
);


ALTER TABLE public.offers_technologies OWNER TO luisg;

--
-- Name: recruiters; Type: TABLE; Schema: public; Owner: luisg
--

CREATE TABLE public.recruiters (
    id uuid NOT NULL,
    description character varying(500),
    contact_email character varying(254) NOT NULL,
    status boolean NOT NULL,
    created timestamp with time zone NOT NULL,
    modified timestamp with time zone NOT NULL,
    company_id uuid NOT NULL,
    creator_id uuid NOT NULL,
    modifier_id uuid NOT NULL,
    user_id uuid NOT NULL
);


ALTER TABLE public.recruiters OWNER TO luisg;

--
-- Name: technologies; Type: TABLE; Schema: public; Owner: luisg
--

CREATE TABLE public.technologies (
    id uuid NOT NULL,
    name character varying(100) NOT NULL,
    status boolean NOT NULL,
    created timestamp with time zone NOT NULL,
    modified timestamp with time zone NOT NULL,
    creator_id uuid,
    modifier_id uuid
);


ALTER TABLE public.technologies OWNER TO luisg;

--
-- Name: token_blacklist_blacklistedtoken; Type: TABLE; Schema: public; Owner: luisg
--

CREATE TABLE public.token_blacklist_blacklistedtoken (
    id bigint NOT NULL,
    blacklisted_at timestamp with time zone NOT NULL,
    token_id bigint NOT NULL
);


ALTER TABLE public.token_blacklist_blacklistedtoken OWNER TO luisg;

--
-- Name: token_blacklist_blacklistedtoken_id_seq; Type: SEQUENCE; Schema: public; Owner: luisg
--

ALTER TABLE public.token_blacklist_blacklistedtoken ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.token_blacklist_blacklistedtoken_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: token_blacklist_outstandingtoken; Type: TABLE; Schema: public; Owner: luisg
--

CREATE TABLE public.token_blacklist_outstandingtoken (
    id bigint NOT NULL,
    token text NOT NULL,
    created_at timestamp with time zone,
    expires_at timestamp with time zone NOT NULL,
    user_id uuid,
    jti character varying(255) NOT NULL
);


ALTER TABLE public.token_blacklist_outstandingtoken OWNER TO luisg;

--
-- Name: token_blacklist_outstandingtoken_id_seq; Type: SEQUENCE; Schema: public; Owner: luisg
--

ALTER TABLE public.token_blacklist_outstandingtoken ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.token_blacklist_outstandingtoken_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: luisg
--

CREATE TABLE public.users (
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    id uuid NOT NULL,
    modified timestamp with time zone NOT NULL,
    creator_id uuid,
    modifier_id uuid
);


ALTER TABLE public.users OWNER TO luisg;

--
-- Name: users_groups; Type: TABLE; Schema: public; Owner: luisg
--

CREATE TABLE public.users_groups (
    id integer NOT NULL,
    user_id uuid NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.users_groups OWNER TO luisg;

--
-- Name: users_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: luisg
--

ALTER TABLE public.users_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_user_permissions; Type: TABLE; Schema: public; Owner: luisg
--

CREATE TABLE public.users_user_permissions (
    id integer NOT NULL,
    user_id uuid NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.users_user_permissions OWNER TO luisg;

--
-- Name: users_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: luisg
--

ALTER TABLE public.users_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: applications; Type: TABLE DATA; Schema: public; Owner: luisg
--

COPY public.applications (id, status, created, modified, creator_id, modifier_id, candidate_id, offer_id) FROM stdin;
882dbfc8-7458-49b8-89c1-d07ffac2d846	pending	2026-07-09 00:47:45.284442+00	2026-07-09 00:47:45.284455+00	62826344-37f2-4166-b8cb-ec428b49c131	62826344-37f2-4166-b8cb-ec428b49c131	b010f66b-a4d2-4c7a-9364-46c8ac980d4c	0856b353-ff6f-409b-aae9-849ecb539bf8
\.


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: luisg
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: luisg
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: luisg
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add content type	4	add_contenttype
14	Can change content type	4	change_contenttype
15	Can delete content type	4	delete_contenttype
16	Can view content type	4	view_contenttype
17	Can add session	5	add_session
18	Can change session	5	change_session
19	Can delete session	5	delete_session
20	Can view session	5	view_session
21	Can add user	6	add_user
22	Can change user	6	change_user
23	Can delete user	6	delete_user
24	Can view user	6	view_user
25	Can add candidate	7	add_candidate
26	Can change candidate	7	change_candidate
27	Can delete candidate	7	delete_candidate
28	Can view candidate	7	view_candidate
29	Can add company	8	add_company
30	Can change company	8	change_company
31	Can delete company	8	delete_company
32	Can view company	8	view_company
33	Can add location	9	add_location
34	Can change location	9	change_location
35	Can delete location	9	delete_location
36	Can view location	9	view_location
37	Can add offer	10	add_offer
38	Can change offer	10	change_offer
39	Can delete offer	10	delete_offer
40	Can view offer	10	view_offer
41	Can add application	11	add_application
42	Can change application	11	change_application
43	Can delete application	11	delete_application
44	Can view application	11	view_application
45	Can add recruiter	12	add_recruiter
46	Can change recruiter	12	change_recruiter
47	Can delete recruiter	12	delete_recruiter
48	Can view recruiter	12	view_recruiter
49	Can add technology	13	add_technology
50	Can change technology	13	change_technology
51	Can delete technology	13	delete_technology
52	Can view technology	13	view_technology
53	Can add offer technology	14	add_offertechnology
54	Can change offer technology	14	change_offertechnology
55	Can delete offer technology	14	delete_offertechnology
56	Can view offer technology	14	view_offertechnology
57	Can add blacklisted token	15	add_blacklistedtoken
58	Can change blacklisted token	15	change_blacklistedtoken
59	Can delete blacklisted token	15	delete_blacklistedtoken
60	Can view blacklisted token	15	view_blacklistedtoken
61	Can add outstanding token	16	add_outstandingtoken
62	Can change outstanding token	16	change_outstandingtoken
63	Can delete outstanding token	16	delete_outstandingtoken
64	Can view outstanding token	16	view_outstandingtoken
\.


--
-- Data for Name: candidates; Type: TABLE DATA; Schema: public; Owner: luisg
--

COPY public.candidates (id, description, seniority, experience_years, status, created, modified, creator_id, modifier_id, user_id) FROM stdin;
b010f66b-a4d2-4c7a-9364-46c8ac980d4c	Desarrollador frontend con experiencia en React y Astro	trainee	1	t	2026-06-30 14:00:48.191918+00	2026-06-30 14:00:48.191933+00	62826344-37f2-4166-b8cb-ec428b49c131	62826344-37f2-4166-b8cb-ec428b49c131	62826344-37f2-4166-b8cb-ec428b49c131
bef535f0-281a-493f-aade-ae4d8625f60e	Desarrollador fullstack	senior	10	t	2026-06-30 15:53:47.760537+00	2026-06-30 15:53:47.760548+00	91300142-f861-40ff-8910-e413ed0c6b57	91300142-f861-40ff-8910-e413ed0c6b57	91300142-f861-40ff-8910-e413ed0c6b57
\.


--
-- Data for Name: companies; Type: TABLE DATA; Schema: public; Owner: luisg
--

COPY public.companies (id, name, status, created, modified, creator_id, modifier_id) FROM stdin;
e23536a9-2d96-4e5d-b3af-f1dde10bd5ff	GLOBANT	t	2026-06-30 04:16:04.449274+00	2026-06-30 04:16:04.449284+00	b2a7abf6-66a3-4559-9f79-32a7b071aa39	b2a7abf6-66a3-4559-9f79-32a7b071aa39
90efd7e9-0c81-469c-8641-79379d1de664	MERCADO LIBRE	t	2026-06-30 04:16:04.450243+00	2026-06-30 04:16:04.45025+00	b2a7abf6-66a3-4559-9f79-32a7b071aa39	b2a7abf6-66a3-4559-9f79-32a7b071aa39
92a1e2f6-28fc-4ea8-a650-203155fb118c	RAPPI	t	2026-06-30 04:16:04.451006+00	2026-06-30 04:16:04.451013+00	b2a7abf6-66a3-4559-9f79-32a7b071aa39	b2a7abf6-66a3-4559-9f79-32a7b071aa39
23d15f26-87bf-491e-a725-985ead5e30e4	NTT DATA	t	2026-06-30 04:16:04.451821+00	2026-06-30 04:16:04.451828+00	b2a7abf6-66a3-4559-9f79-32a7b071aa39	b2a7abf6-66a3-4559-9f79-32a7b071aa39
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: luisg
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: luisg
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	contenttypes	contenttype
5	sessions	session
6	jobs	user
7	jobs	candidate
8	jobs	company
9	jobs	location
10	jobs	offer
11	jobs	application
12	jobs	recruiter
13	jobs	technology
14	jobs	offertechnology
15	token_blacklist	blacklistedtoken
16	token_blacklist	outstandingtoken
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: luisg
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-06-30 04:15:46.402778+00
2	contenttypes	0002_remove_content_type_name	2026-06-30 04:15:46.405997+00
3	auth	0001_initial	2026-06-30 04:15:46.425242+00
4	auth	0002_alter_permission_name_max_length	2026-06-30 04:15:46.427485+00
5	auth	0003_alter_user_email_max_length	2026-06-30 04:15:46.430188+00
6	auth	0004_alter_user_username_opts	2026-06-30 04:15:46.43268+00
7	auth	0005_alter_user_last_login_null	2026-06-30 04:15:46.435225+00
8	auth	0006_require_contenttypes_0002	2026-06-30 04:15:46.436189+00
9	auth	0007_alter_validators_add_error_messages	2026-06-30 04:15:46.438858+00
10	auth	0008_alter_user_username_max_length	2026-06-30 04:15:46.441631+00
11	auth	0009_alter_user_last_name_max_length	2026-06-30 04:15:46.444358+00
12	auth	0010_alter_group_name_max_length	2026-06-30 04:15:46.447369+00
13	auth	0011_update_proxy_permissions	2026-06-30 04:15:46.450185+00
14	auth	0012_alter_user_first_name_max_length	2026-06-30 04:15:46.453381+00
15	jobs	0001_initial	2026-06-30 04:15:46.575089+00
16	admin	0001_initial	2026-06-30 04:15:46.588255+00
17	admin	0002_logentry_remove_auto_add	2026-06-30 04:15:46.594684+00
18	admin	0003_logentry_add_action_flag_choices	2026-06-30 04:15:46.601135+00
19	sessions	0001_initial	2026-06-30 04:15:46.607203+00
20	token_blacklist	0001_initial	2026-06-30 04:15:46.628653+00
21	token_blacklist	0002_outstandingtoken_jti_hex	2026-06-30 04:15:46.635585+00
22	token_blacklist	0003_auto_20171017_2007	2026-06-30 04:15:46.644156+00
23	token_blacklist	0004_auto_20171017_2013	2026-06-30 04:15:46.65475+00
24	token_blacklist	0005_remove_outstandingtoken_jti	2026-06-30 04:15:46.66223+00
25	token_blacklist	0006_auto_20171017_2113	2026-06-30 04:15:46.669958+00
26	token_blacklist	0007_auto_20171017_2214	2026-06-30 04:15:46.702698+00
27	token_blacklist	0008_migrate_to_bigautofield	2026-06-30 04:15:46.726629+00
28	token_blacklist	0010_fix_migrate_to_bigautofield	2026-06-30 04:15:46.736512+00
29	token_blacklist	0011_linearizes_history	2026-06-30 04:15:46.73758+00
30	token_blacklist	0012_alter_outstandingtoken_user	2026-06-30 04:15:46.744321+00
31	jobs	0002_remove_offer_description_offer_description_detail	2026-07-06 17:20:46.377887+00
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: luisg
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
\.


--
-- Data for Name: locations; Type: TABLE DATA; Schema: public; Owner: luisg
--

COPY public.locations (id, name, status, created, modified, creator_id, modifier_id) FROM stdin;
1a6df52c-e33a-43ca-8539-43810f28293a	LIMA, PERÚ	t	2026-06-30 04:16:04.452775+00	2026-06-30 04:16:04.452782+00	b2a7abf6-66a3-4559-9f79-32a7b071aa39	b2a7abf6-66a3-4559-9f79-32a7b071aa39
7eaa2e19-9f58-445e-916a-fae402d3a80e	BUENOS AIRES, ARGENTINA	t	2026-06-30 04:16:04.453841+00	2026-06-30 04:16:04.453849+00	b2a7abf6-66a3-4559-9f79-32a7b071aa39	b2a7abf6-66a3-4559-9f79-32a7b071aa39
f1da18f9-2097-4376-adc8-ceeb15b323c4	BOGOTÁ, COLOMBIA	t	2026-06-30 04:16:04.454624+00	2026-06-30 04:16:04.454631+00	b2a7abf6-66a3-4559-9f79-32a7b071aa39	b2a7abf6-66a3-4559-9f79-32a7b071aa39
\.


--
-- Data for Name: offers; Type: TABLE DATA; Schema: public; Owner: luisg
--

COPY public.offers (id, title, modality, seniority, status, salary, created, modified, creator_id, location_id, modifier_id, recruiter_id, description_detail) FROM stdin;
0856b353-ff6f-409b-aae9-849ecb539bf8	BACKEND PYTHON TRAINEE	remote	trainee	t	1200.00	2026-07-06 20:51:40.287248+00	2026-07-06 20:51:40.287262+00	62826344-37f2-4166-b8cb-ec428b49c131	1a6df52c-e33a-43ca-8539-43810f28293a	62826344-37f2-4166-b8cb-ec428b49c131	45d2cf54-da09-4aa4-9d4f-40cef46ede1c	¡Únete a nuestro equipo de ingeniería como Trainee! Somos una compañía global enfocada en transformar la industria financiera a través de la tecnología. Estamos buscando un profesional apasionado por el desarrollo backend que busque su primera gran oportunidad en el sector IT para incorporarse a nuestros proyectos principales. En este puesto, aprenderás a diseñar, construir y mantener APIs escalables y servicios robustos que soportan miles de transacciones diarias. TUS RESPONSABILIDADES INCLUYEN: 1) Apoyo en la arquitectura y desarrollo de nuevos microservicios utilizando las mejores prácticas de la industria y el diseño de bases de datos. 2) Optimización de consultas bajo la mentoría de desarrolladores Senior. 3) Colaboración estrecha con equipos de frontend y producto para definir especificaciones técnicas precisas. 4) Mantenimiento del código base y creación de pruebas unitarias. PERFIL IDEAL: Valoramos profundamente a los candidatos que demuestran una mentalidad analítica, capacidad para resolver problemas y un fuerte deseo de aprender constantemente. Deberás tener sólidas bases teóricas en algoritmos y un excelente manejo de la lógica de programación. NUESTRA OFERTA: Trabajarás en un ambiente dinámico, inclusivo y multicultural donde el aprendizaje es lo más importante. Ofrecemos un salario competitivo para perfiles de entrada, revisiones periódicas, seguro de salud premium, días libres adicionales, y un estipendio anual para tu desarrollo profesional.
4daa300e-8f86-49d6-ac8a-7f206e8fa2ee	FRONTEND REACT DEVELOPER (JUNIOR)	hybrid	junior	t	2000.00	2026-07-06 20:51:57.448193+00	2026-07-06 20:51:57.448203+00	62826344-37f2-4166-b8cb-ec428b49c131	7eaa2e19-9f58-445e-916a-fae402d3a80e	62826344-37f2-4166-b8cb-ec428b49c131	45d2cf54-da09-4aa4-9d4f-40cef46ede1c	¿Te apasiona crear interfaces de usuario increíbles y experiencias interactivas de primer nivel? Somos una agencia de producto digital de rápido crecimiento y estamos buscando a un desarrollador junior especializado en frontend para unirse a nuestra división de innovación. Tu misión será dar vida a diseños complejos, asegurando interfaces responsivas, accesibles y altamente optimizadas. TUS RESPONSABILIDADES PRINCIPALES INCLUYEN: 1) Traducir diseños de UI/UX en código de alta calidad, modular y mantenible. 2) Implementar flujos de estado en aplicaciones web modernas, garantizando una experiencia de usuario fluida y sin interrupciones. 3) Optimizar aplicaciones para alcanzar la máxima velocidad y escalabilidad en diversos dispositivos y navegadores. 4) Trabajar de la mano con el equipo de backend para integrar APIs RESTful, consumiendo y gestionando datos de forma eficiente. PERFIL IDEAL: Buscamos a alguien con una fuerte sensibilidad hacia el diseño y la usabilidad, que preste atención a los detalles sin comprometer el rendimiento técnico. Debes sentirte cómodo trabajando en un entorno ágil, participando en ceremonias Scrum y aprendiendo continuamente de tus compañeros de equipo. NUESTRA OFERTA: Nos enorgullece fomentar una cultura de trabajo basada en la empatía, el respeto y la innovación constante. Además de una compensación económica muy atractiva, te ofrecemos horario flexible, clases de inglés y acceso a plataformas de aprendizaje online de gran prestigio.
0efcb2c0-b7d0-417f-bc0a-3351d4c6434d	FULLSTACK DJANGO & REACT ENGINEER	presential	mid	t	3800.00	2026-07-06 20:52:23.039713+00	2026-07-06 20:52:23.039729+00	62826344-37f2-4166-b8cb-ec428b49c131	f1da18f9-2097-4376-adc8-ceeb15b323c4	62826344-37f2-4166-b8cb-ec428b49c131	45d2cf54-da09-4aa4-9d4f-40cef46ede1c	¡Estamos en la búsqueda de talento excepcional para potenciar nuestro equipo de tecnología multiplataforma! Somos una startup respaldada por importantes firmas de capital de riesgo, dedicada a revolucionar el comercio electrónico en toda Latinoamérica. Como miembro clave de nuestro equipo Mid-level, tendrás un impacto directo tanto en la lógica de negocio subyacente como en la interfaz que interactúa con el usuario final. TUS RESPONSABILIDADES PRINCIPALES INCLUYEN: 1) Diseñar, desarrollar e implementar funcionalidades completas desde la base de datos hasta el navegador web del cliente. 2) Integrar soluciones de pasarelas de pago, sistemas de inventario en tiempo real y herramientas analíticas críticas. 3) Asegurar la escalabilidad horizontal y vertical de nuestra plataforma en la nube, monitoreando el estado general de la aplicación. 4) Liderar pequeñas iniciativas de código y aportar soluciones creativas a desafíos técnicos diarios. PERFIL IDEAL: Eres una persona proactiva, autónoma y apasionada por entender el producto en su totalidad. No solo te preocupas por el código, sino por cómo este resuelve problemas reales de los usuarios. Destacas por tu capacidad de adaptarte a nuevos entornos y proponer mejoras. NUESTRA OFERTA: Te unirás a un grupo de personas apasionadas en una cultura donde las mejores ideas siempre ganan. Ofrecemos acciones (equity) de la empresa para que seas dueño de tu éxito, vacaciones ilimitadas gestionadas con responsabilidad y plan de salud integral para tu familia.
d1d88d6f-e679-4748-9a0c-5ba5d3257cc1	SENIOR POSTGRESQL & PYTHON ARCHITECT	remote	senior	t	6500.00	2026-07-06 20:53:32.400201+00	2026-07-06 20:53:32.400216+00	b7ae581b-2e5a-4638-906f-2bc4f115dcde	1a6df52c-e33a-43ca-8539-43810f28293a	b7ae581b-2e5a-4638-906f-2bc4f115dcde	7d6bc49b-247a-4869-a214-0b5072adf16d	Buscamos a un Arquitecto de Software y Desarrollador Senior enfocado en el ecosistema de Python y PostgreSQL. Somos una empresa líder en procesamiento de grandes volúmenes de datos que transforma la industria logística global. En este rol crítico, serás el máximo responsable de asegurar que nuestras bases de datos y la capa de servicios backend operen con una eficiencia del 99.99%. TUS RESPONSABILIDADES INCLUIRÁN: 1) Arquitectura profunda de sistemas distribuidos y diseño de esquemas complejos en PostgreSQL para soportar alta concurrencia. 2) Mentoría y capacitación de equipos Mid y Junior, elevando la calidad técnica de todo el departamento de ingeniería. 3) Identificar cuellos de botella mediante profiling de bases de datos y refactorización de código legado en Python puro y frameworks modernos. 4) Liderar la migración de arquitecturas monolíticas hacia microservicios totalmente desplegados en infraestructuras cloud nativas. PERFIL REQUERIDO: Debes poseer más de cinco años de experiencia comprobable en posiciones similares, demostrando un profundo entendimiento de bloqueos, transacciones, aislamiento y optimización extrema de consultas SQL. Buscamos a un líder innato que predique con el ejemplo. BENEFICIOS: Te brindamos la posibilidad de trabajar 100% en remoto desde cualquier lugar del país, con un salario tope de gama en el mercado, bonos por cumplimiento de métricas trimestrales, y la entrega de equipamiento ergonómico completo (silla, monitores 4K, y laptop de última generación) para tu oficina en casa.
e9cce5da-ecec-4e50-aa5f-d7b5ff5093b4	LEAD REACT & TYPESCRIPT DEVELOPER	remote	lead	t	8000.00	2026-07-06 20:53:54.399615+00	2026-07-06 20:53:54.399627+00	b7ae581b-2e5a-4638-906f-2bc4f115dcde	7eaa2e19-9f58-445e-916a-fae402d3a80e	b7ae581b-2e5a-4638-906f-2bc4f115dcde	7d6bc49b-247a-4869-a214-0b5072adf16d	Asume el liderazgo de nuestro departamento de Frontend. Como Tech Lead, guiarás la evolución técnica y estética de nuestras plataformas web corporativas utilizadas por empresas del sector Fortune 500. Necesitamos a un experto que respire React y TypeScript y que entienda la importancia de las arquitecturas escalables a largo plazo. TUS FUNCIONES Y RESPONSABILIDADES: 1) Liderar técnica y humanamente a un equipo de 8-10 desarrolladores frontend, realizando evaluaciones de desempeño y planes de carrera. 2) Establecer los estándares de codificación, los linters, y los pipelines de CI/CD para todo el código que toca el navegador. 3) Diseñar sistemas de diseño (Design Systems) robustos y accesibles que estandaricen la UI en múltiples productos de la compañía. 4) Trabajar codo a codo con los directores de Producto y Diseño para garantizar que la viabilidad técnica esté alineada con la visión del negocio. EL CANDIDATO IDEAL: Eres un comunicador excepcional y un puente entre el negocio y la tecnología. Tienes un dominio absoluto de TypeScript avanzado, patrones de diseño en React, y gestión de estado compleja. Entiendes las métricas de Core Web Vitals a la perfección y sabes cómo optimizarlas. LO QUE OFRECEMOS: Un paquete salarial altamente competitivo en moneda dura, participación en los beneficios anuales de la empresa, seguro médico premium para grupo familiar completo, presupuesto anual libre de $2000 USD para asistir a la conferencia tecnológica internacional de tu elección (viajes y hospedaje cubiertos).
bd675ce3-73b6-4ef7-9fd0-c3652c867825	DJANGO BACKEND DEVELOPER - JUNIOR	hybrid	junior	t	1800.00	2026-07-06 20:54:01.787892+00	2026-07-06 20:54:01.787905+00	b7ae581b-2e5a-4638-906f-2bc4f115dcde	f1da18f9-2097-4376-adc8-ceeb15b323c4	b7ae581b-2e5a-4638-906f-2bc4f115dcde	7d6bc49b-247a-4869-a214-0b5072adf16d	Inicia tu carrera profesional desarrollando el backend de aplicaciones que impactan la vida de miles de personas. En nuestra empresa del sector educativo (EdTech), estamos creando la nueva generación de aulas virtuales y plataformas de e-learning. Como desarrollador Junior enfocado en Django, tendrás el espacio perfecto para crecer y consolidar tus conocimientos. LO QUE HARÁS DÍA A DÍA: 1) Participar en la creación de nuevos endpoints RESTful utilizando Django Rest Framework (DRF) bajo la supervisión de nuestros arquitectos. 2) Modificar y extender los esquemas de bases de datos PostgreSQL para acomodar nuevas características del sistema de gestión de estudiantes. 3) Escribir pruebas unitarias exhaustivas para garantizar que nuestro código sea confiable y seguro frente a cambios futuros. 4) Aprender a utilizar herramientas modernas de orquestación y despliegue en la nube, participando activamente en los code reviews de la empresa. LO QUE BUSCAMOS EN TI: Pasión inagotable por la programación y una base sólida en Python. No necesitas años de experiencia, pero sí haber construido proyectos personales o universitarios interesantes que demuestren tus habilidades prácticas con Django. Valoramos la proactividad y la capacidad de recibir feedback constructivo. NUESTROS BENEFICIOS: Te ofrecemos un ambiente de trabajo híbrido con oficinas modernas y áreas de esparcimiento. Brindamos capacitaciones semanales internas impartidas por nuestros leads, seguro médico corporativo y viernes de jornada corta durante los meses de verano.
f530c204-fd5f-43cd-a82f-edb3ae65edbd	LEAD FULLSTACK SOFTWARE ENGINEER	presential	lead	t	9500.00	2026-07-06 20:55:19.19295+00	2026-07-06 20:55:19.19296+00	b92c4cc7-be25-400f-bd96-d60ab1e8c187	1a6df52c-e33a-43ca-8539-43810f28293a	b92c4cc7-be25-400f-bd96-d60ab1e8c187	17981f25-e115-4525-99ee-376142ae4253	Dirige la construcción tecnológica de la próxima gran SuperApp de la región. Estamos buscando a un Líder Técnico Fullstack que no le tenga miedo a ensuciarse las manos con el código, pero que también posea la visión estratégica para escalar un producto desde miles a millones de usuarios concurrentes. TU ROL Y DESAFÍOS: 1) Ser el referente técnico definitivo en la stack completa de la empresa (Python, Django, React, TypeScript y PostgreSQL). 2) Diseñar y documentar la arquitectura de software de extremo a extremo, evaluando y mitigando riesgos técnicos. 3) Liderar células ágiles de desarrollo presencial, fomentando una cultura de excelencia técnica y entrega continua (Continuous Delivery). 4) Evaluar el rendimiento sistémico, garantizando que tanto el renderizado en frontend como las consultas a bases de datos y la lógica en backend funcionen como una maquinaria perfectamente sincronizada. PERFIL ESPERADO: Más de siete años de experiencia en desarrollo de software, con al menos dos años en roles de liderazgo formal. Capacidad comprobada para diseñar APIs robustas y aplicaciones frontend ricas en funcionalidades complejas. Eres un mentor por naturaleza y tienes un historial de haber llevado productos digitales exitosos desde su concepción hasta su comercialización. QUÉ OFRECEMOS: Compensación salarial del percentil más alto del mercado local, un rol con alto nivel de autonomía y toma de decisiones a nivel directivo, paquete generoso de acciones (stock options) en una empresa en fase pre-IPO, y beneficios corporativos exclusivos de nivel ejecutivo.
2961d6cb-6e63-4aa0-8ab4-da3094abc30a	MID-LEVEL FRONTEND DEVELOPER (REACT/TS)	remote	mid	t	3500.00	2026-07-06 20:55:25.633912+00	2026-07-06 20:55:25.633923+00	b92c4cc7-be25-400f-bd96-d60ab1e8c187	7eaa2e19-9f58-445e-916a-fae402d3a80e	b92c4cc7-be25-400f-bd96-d60ab1e8c187	17981f25-e115-4525-99ee-376142ae4253	Súmate al equipo encargado de construir el futuro de la gestión de recursos humanos a nivel global. Como Desarrollador Frontend Mid-Level, jugarás un rol crítico en la implementación de interfaces de usuario para nuestra plataforma SaaS que utilizan millones de empleados diariamente. TUS RESPONSABILIDADES DIARIAS: 1) Desarrollar nuevos módulos interactivos de recursos humanos utilizando React y TypeScript, asegurando la tipificación estricta de todo el proyecto. 2) Refactorizar componentes existentes para mejorar su reusabilidad y disminuir la carga del bundle final. 3) Integrar herramientas de analítica y monitoreo de errores en el lado del cliente (como Sentry o Datadog) para garantizar la estabilidad de la aplicación. 4) Trabajar metodológicamente con el equipo de Diseño usando herramientas como Figma para iterar rápidamente sobre prototipos interactivos. PERFIL QUE BUSCAMOS: Cuentas con experiencia sólida (2 a 4 años) construyendo SPAs (Single Page Applications) complejas. Entiendes las diferencias entre componentes de presentación y contenedores, y sabes cómo administrar estados globales sin acoplar innecesariamente el código. Cuidas el performance y el diseño accesible (a11y). NUESTRA PROPUESTA DE VALOR: Trabajo 100% remoto de forma permanente, horarios flexibles enfocados completamente en la consecución de objetivos y no en horas calentando la silla. Bono anual de desempeño, suscripción gratuita a gimnasios y plataformas de salud mental, y una cultura laboral transparente que valora profundamente el equilibrio entre la vida personal y laboral.
c062b7ea-bd34-4669-be6e-54e74e00cdfb	MID BACKEND PYTHON DEVELOPER	remote	mid	t	4000.00	2026-07-06 20:55:30.475362+00	2026-07-06 20:55:30.475376+00	b92c4cc7-be25-400f-bd96-d60ab1e8c187	f1da18f9-2097-4376-adc8-ceeb15b323c4	b92c4cc7-be25-400f-bd96-d60ab1e8c187	17981f25-e115-4525-99ee-376142ae4253	Únete a una startup fintech innovadora que está democratizando el acceso a inversiones en mercados emergentes. Estamos en la búsqueda de un Desarrollador Backend Mid-Level experto en Python y bases de datos relacionales para fortalecer nuestro motor transaccional. TUS DESAFÍOS PRINCIPALES: 1) Desarrollar algoritmos de conciliación bancaria y procesamiento de pagos en tiempo real utilizando Python. 2) Estructurar, optimizar y mantener bases de datos en PostgreSQL, garantizando la consistencia y seguridad de la información financiera sensible. 3) Crear integraciones seguras mediante APIs con proveedores financieros internacionales y pasarelas de pago de terceros. 4) Participar en la evolución de nuestra arquitectura hacia un modelo basado en eventos (Event-Driven Architecture) para mejorar la escalabilidad del sistema. REQUISITOS DEL CANDIDATO: Posees entre 2 y 4 años de experiencia profesional centrada en el desarrollo backend. Tienes conocimientos intermedios o avanzados sobre seguridad en aplicaciones web, prevención de vulnerabilidades (OWASP), criptografía básica y manejo seguro de secretos. Entiendes profundamente el funcionamiento de los motores SQL modernos. BENEFICIOS Y CULTURA: Disfruta de la comodidad de trabajar en remoto total. Brindamos un paquete de beneficios que incluye seguro médico internacional, programa de matching para tus propias inversiones en la plataforma, presupuesto para adecuación de home office y un estricto respeto por tus horarios fuera del trabajo para prevenir el burnout.
ee4d4440-aa67-4618-bfee-01f34267379c	SENIOR FULL STACK ENGINEER	hybrid	senior	t	6800.00	2026-07-06 20:56:19.968191+00	2026-07-06 20:56:19.968201+00	91300142-f861-40ff-8910-e413ed0c6b57	1a6df52c-e33a-43ca-8539-43810f28293a	91300142-f861-40ff-8910-e413ed0c6b57	0ba99764-3d89-4bc3-99da-e3eee92ea121	Buscamos a un Ingeniero de Software Full Stack Senior para unirse a nuestro laboratorio de investigación y desarrollo (I+D) en la industria de la salud tecnológica (HealthTech). Tendrás la responsabilidad de liderar el desarrollo de herramientas de telemedicina que salvan vidas, manejando todo el flujo tecnológico. TUS RESPONSABILIDADES: 1) Diseñar arquitecturas complejas que integren sistemas legacy de hospitales (usando Python/Django) con interfaces modernas para médicos y pacientes (desarrolladas en React/TypeScript). 2) Modelar complejas bases de datos en PostgreSQL para el manejo seguro de historias clínicas electrónicas bajo estándares de cumplimiento internacionales (como HIPAA). 3) Establecer prácticas de DevOps y automatización de pruebas para asegurar que el despliegue de software médico sea seguro e ininterrumpido. 4) Guiar el análisis técnico de requerimientos funcionales y liderar iniciativas de innovación tecnológica interna. LO QUE NECESITAS PARA TRIUNFAR AQUÍ: Más de 5 años construyendo aplicaciones web completas a nivel de producción. Capacidad comprobada para pensar de manera sistémica, equilibrando deudas técnicas con la entrega rápida de valor. Excelentes habilidades de comunicación y empatía, ya que colaborarás constantemente con profesionales médicos no técnicos. LO QUE TE OFRECEMOS: Modelo de trabajo híbrido con oficinas premium. Además de un sueldo top en el mercado, tendrás un seguro de salud privado completo que incluye odontología y visión, bonificaciones por hitos de proyecto, y un mes entero (30 días) de vacaciones remuneradas al año.
7d9d2c21-0b8e-4a23-9a0c-650a4a28ef32	TRAINEE UI/UX & REACT DEVELOPER	presential	trainee	t	1000.00	2026-07-06 20:56:26.385144+00	2026-07-06 20:56:26.385157+00	91300142-f861-40ff-8910-e413ed0c6b57	7eaa2e19-9f58-445e-916a-fae402d3a80e	91300142-f861-40ff-8910-e413ed0c6b57	0ba99764-3d89-4bc3-99da-e3eee92ea121	¡Abre las puertas de tu carrera profesional en el mundo del desarrollo de producto digital! Nuestra agencia creativa busca un Trainee con gran pasión por el diseño UI/UX y la programación frontend para formarlo como un desarrollador React de alto nivel. Aprenderás de primera mano cómo es el ciclo completo desde el diseño en herramientas visuales hasta el despliegue en producción. TUS TAREAS DE APRENDIZAJE: 1) Colaborarás con diseñadores senior para traducir maquetas visuales en componentes funcionales de React puro. 2) Aprenderás a estructurar proyectos frontend, manejar repositorios en Git, y aplicar estilos modernos y animaciones fluidas CSS. 3) Entenderás la interacción con el backend consumiendo APIs básicas. 4) Participarás en sesiones de brainstorming y pruebas de usabilidad, entendiendo la importancia del feedback del usuario real. EL PERFIL IDEAL: Eres un recién graduado, estudiante de últimos ciclos o autodidacta con un portafolio de proyectos personales atractivos. Te fascina el diseño visual pero has descubierto que programar esas interfaces es aún más divertido. Tienes ganas increíbles de aprender, eres curioso y no temes equivocarte, ya que consideramos los errores como oportunidades de aprendizaje. NUESTROS BENEFICIOS: Un programa de mentoría estructurado de 6 meses con posibilidades de contratación permanente como Junior. Modalidad presencial en oficinas pet-friendly ubicadas en una zona céntrica, con snacks, bebidas gratuitas, viernes de pizza, y un ambiente altamente creativo, relajado y juvenil.
b7a84dff-3d9a-4e0f-84b6-b53aff0c0205	TECH LEAD - PYTHON/DJANGO BACKEND	remote	lead	t	8500.00	2026-07-06 20:56:34.342124+00	2026-07-06 20:56:34.342135+00	91300142-f861-40ff-8910-e413ed0c6b57	f1da18f9-2097-4376-adc8-ceeb15b323c4	91300142-f861-40ff-8910-e413ed0c6b57	0ba99764-3d89-4bc3-99da-e3eee92ea121	Lidera la ingeniería backend de una de las plataformas SaaS B2B de mayor crecimiento en la región. Estamos buscando un Líder Técnico especializado en el framework Django para estructurar nuestros equipos de desarrollo, definir nuestra ruta tecnológica a futuro y resolver desafíos de escalabilidad extremos. TUS PRINCIPALES DESAFÍOS: 1) Ser responsable por la arquitectura general del backend, asegurando alta disponibilidad, seguridad y tolerancia a fallos en nuestros clusters. 2) Mentorear, dirigir y hacer crecer a un equipo de ingenieros backend, estableciendo objetivos claros y fomentando un ambiente de mejora continua. 3) Optimizar a niveles profundos nuestra base de datos PostgreSQL, planificando estrategias de particionamiento, sharding y caching. 4) Colaborar a nivel ejecutivo con los fundadores para alinear las estrategias técnicas con los ambiciosos objetivos de negocio trimestrales. PERFIL DEMANDADO: Profesional con una vasta trayectoria en Python y un profundo dominio de Django y su ecosistema. Experiencia demostrada escalando aplicaciones a millones de peticiones diarias. Liderazgo comprobado, capacidad para destrabar problemas complejos, y habilidad para comunicar conceptos técnicos a stakeholders no técnicos. LA PROPUESTA: Posición remota desde cualquier parte. Paquete de compensación ejecutiva que supera el mercado, generoso paquete de acciones (stock options) para que te asocies a nuestro éxito a largo plazo, presupuesto ilimitado en literatura técnica, capacitaciones ejecutivas, seguro médico premium y 4 semanas de vacaciones al año.
\.


--
-- Data for Name: offers_technologies; Type: TABLE DATA; Schema: public; Owner: luisg
--

COPY public.offers_technologies (id, offer_id, technology_id) FROM stdin;
80c80b10-3823-47a5-872b-26703dcac59f	0856b353-ff6f-409b-aae9-849ecb539bf8	355858bf-a862-463f-a29d-90b54e39b33f
89eda072-1888-4bb5-86eb-858f5238a709	0856b353-ff6f-409b-aae9-849ecb539bf8	16988627-ae7e-45a4-a8c6-f0ef1e022048
344d4db5-5cc1-4223-a65f-63b62c4805f4	4daa300e-8f86-49d6-ac8a-7f206e8fa2ee	78395a84-20b5-490d-9b94-8518a2caac26
fe2cbd11-351c-4b3d-992a-c8de14d9b655	4daa300e-8f86-49d6-ac8a-7f206e8fa2ee	173ac8a8-b787-42f7-837c-a72c435b4f9f
1d21614a-5c73-4293-bc37-a01ea1f73f5e	0efcb2c0-b7d0-417f-bc0a-3351d4c6434d	49554bf9-70fd-4b4d-8fea-ecb4c32b0ea2
4738daf7-4531-47ba-8f24-ae8182714de2	0efcb2c0-b7d0-417f-bc0a-3351d4c6434d	355858bf-a862-463f-a29d-90b54e39b33f
f101086c-6f58-4740-a70d-173e34c8482d	0efcb2c0-b7d0-417f-bc0a-3351d4c6434d	16988627-ae7e-45a4-a8c6-f0ef1e022048
50272123-9117-4cba-b926-6206b68f7694	0efcb2c0-b7d0-417f-bc0a-3351d4c6434d	78395a84-20b5-490d-9b94-8518a2caac26
ff5600c4-f9b1-40b5-a50e-6d973a6fbca0	d1d88d6f-e679-4748-9a0c-5ba5d3257cc1	355858bf-a862-463f-a29d-90b54e39b33f
402a970f-c40f-4591-8f89-8ebd8605434f	d1d88d6f-e679-4748-9a0c-5ba5d3257cc1	16988627-ae7e-45a4-a8c6-f0ef1e022048
ba852a57-7cb2-4434-8bae-34fd180b32f9	e9cce5da-ecec-4e50-aa5f-d7b5ff5093b4	78395a84-20b5-490d-9b94-8518a2caac26
753c9113-c7da-43b8-a908-7c3e5c3d45a3	e9cce5da-ecec-4e50-aa5f-d7b5ff5093b4	173ac8a8-b787-42f7-837c-a72c435b4f9f
78038ad5-149e-4fda-aa74-f2a2ac42450a	bd675ce3-73b6-4ef7-9fd0-c3652c867825	49554bf9-70fd-4b4d-8fea-ecb4c32b0ea2
e032cca8-6617-44e7-bbe8-89a7ce801d7c	bd675ce3-73b6-4ef7-9fd0-c3652c867825	355858bf-a862-463f-a29d-90b54e39b33f
4b869c73-1da4-4655-8f9f-ce17836674d9	bd675ce3-73b6-4ef7-9fd0-c3652c867825	16988627-ae7e-45a4-a8c6-f0ef1e022048
0f8b35fa-61f2-4733-a753-4e698b2b6a68	f530c204-fd5f-43cd-a82f-edb3ae65edbd	49554bf9-70fd-4b4d-8fea-ecb4c32b0ea2
8bf1911c-de15-421f-a696-7b7647542c7e	f530c204-fd5f-43cd-a82f-edb3ae65edbd	173ac8a8-b787-42f7-837c-a72c435b4f9f
6c6e2e17-7cf2-4c4f-8ffa-e1fa11d8e45a	f530c204-fd5f-43cd-a82f-edb3ae65edbd	78395a84-20b5-490d-9b94-8518a2caac26
67840f1c-0bd0-4dcc-86a4-20b894bc9565	f530c204-fd5f-43cd-a82f-edb3ae65edbd	16988627-ae7e-45a4-a8c6-f0ef1e022048
6005e755-26a7-4e10-b449-dc7525361ed5	f530c204-fd5f-43cd-a82f-edb3ae65edbd	355858bf-a862-463f-a29d-90b54e39b33f
3d71c19b-9d0c-43c7-9bf8-a2f3ecc8df3f	2961d6cb-6e63-4aa0-8ab4-da3094abc30a	78395a84-20b5-490d-9b94-8518a2caac26
617bef0c-d8a5-4c83-8572-9d41832f07e6	2961d6cb-6e63-4aa0-8ab4-da3094abc30a	173ac8a8-b787-42f7-837c-a72c435b4f9f
1a998ec0-f24e-4a44-84f6-93de6997592c	c062b7ea-bd34-4669-be6e-54e74e00cdfb	355858bf-a862-463f-a29d-90b54e39b33f
fff2fc35-ab4a-44f7-bd83-b3518aaa0934	c062b7ea-bd34-4669-be6e-54e74e00cdfb	16988627-ae7e-45a4-a8c6-f0ef1e022048
ff65706b-7126-4566-a516-573395ddb8e6	ee4d4440-aa67-4618-bfee-01f34267379c	49554bf9-70fd-4b4d-8fea-ecb4c32b0ea2
dd4fa9d3-3cc9-4236-a5ba-c050be9d5ce4	ee4d4440-aa67-4618-bfee-01f34267379c	173ac8a8-b787-42f7-837c-a72c435b4f9f
c38d2de1-bbf5-4725-b650-119298441d77	ee4d4440-aa67-4618-bfee-01f34267379c	78395a84-20b5-490d-9b94-8518a2caac26
184f0f08-8794-4fa6-baa4-661b5aff9dc8	ee4d4440-aa67-4618-bfee-01f34267379c	16988627-ae7e-45a4-a8c6-f0ef1e022048
51e5f896-ce4f-4abd-b362-c7a05c5e9e4d	ee4d4440-aa67-4618-bfee-01f34267379c	355858bf-a862-463f-a29d-90b54e39b33f
3208e97b-fd3e-4eef-bf50-3115cdf53c09	7d9d2c21-0b8e-4a23-9a0c-650a4a28ef32	78395a84-20b5-490d-9b94-8518a2caac26
3f963b3e-7e48-4ea1-945b-9e853462e6aa	b7a84dff-3d9a-4e0f-84b6-b53aff0c0205	49554bf9-70fd-4b4d-8fea-ecb4c32b0ea2
c14e0363-fbb8-4ae5-a8dd-a19248c1f085	b7a84dff-3d9a-4e0f-84b6-b53aff0c0205	355858bf-a862-463f-a29d-90b54e39b33f
f5b87dd3-1f88-498f-a329-4c1ee51dcf2d	b7a84dff-3d9a-4e0f-84b6-b53aff0c0205	16988627-ae7e-45a4-a8c6-f0ef1e022048
\.


--
-- Data for Name: recruiters; Type: TABLE DATA; Schema: public; Owner: luisg
--

COPY public.recruiters (id, description, contact_email, status, created, modified, company_id, creator_id, modifier_id, user_id) FROM stdin;
7d6bc49b-247a-4869-a214-0b5072adf16d	Reclutadora con años de experiencia	lucia_apaza@gmail.com	t	2026-06-30 14:06:15.471636+00	2026-06-30 14:06:15.471647+00	92a1e2f6-28fc-4ea8-a650-203155fb118c	b7ae581b-2e5a-4638-906f-2bc4f115dcde	b7ae581b-2e5a-4638-906f-2bc4f115dcde	b7ae581b-2e5a-4638-906f-2bc4f115dcde
17981f25-e115-4525-99ee-376142ae4253	Reclutador poco experimentado	maria_rodriguez@gmail.com	t	2026-06-30 15:48:22.778558+00	2026-06-30 15:48:22.778568+00	23d15f26-87bf-491e-a725-985ead5e30e4	b92c4cc7-be25-400f-bd96-d60ab1e8c187	b92c4cc7-be25-400f-bd96-d60ab1e8c187	b92c4cc7-be25-400f-bd96-d60ab1e8c187
0ba99764-3d89-4bc3-99da-e3eee92ea121	Recruiter con muy buena onda	carlos_perez@gmail.com	t	2026-07-02 21:16:24.156038+00	2026-07-02 21:16:24.15605+00	23d15f26-87bf-491e-a725-985ead5e30e4	91300142-f861-40ff-8910-e413ed0c6b57	91300142-f861-40ff-8910-e413ed0c6b57	91300142-f861-40ff-8910-e413ed0c6b57
45d2cf54-da09-4aa4-9d4f-40cef46ede1c	Busco conectar talento con oportunidades donde realmente puedan crecer. Me enfoco en perfiles de tecnología, desde frontend y backend hasta ingeniería de datos y DevOps. Siempre abierto a conversar sobre nuevos desafíos y proyectos interesantes.	jose_gimenez@example.com	t	2026-07-06 20:23:28.546397+00	2026-07-06 20:23:28.546413+00	e23536a9-2d96-4e5d-b3af-f1dde10bd5ff	62826344-37f2-4166-b8cb-ec428b49c131	62826344-37f2-4166-b8cb-ec428b49c131	62826344-37f2-4166-b8cb-ec428b49c131
\.


--
-- Data for Name: technologies; Type: TABLE DATA; Schema: public; Owner: luisg
--

COPY public.technologies (id, name, status, created, modified, creator_id, modifier_id) FROM stdin;
355858bf-a862-463f-a29d-90b54e39b33f	PYTHON	t	2026-06-30 04:16:04.455573+00	2026-06-30 04:16:04.45558+00	b2a7abf6-66a3-4559-9f79-32a7b071aa39	b2a7abf6-66a3-4559-9f79-32a7b071aa39
49554bf9-70fd-4b4d-8fea-ecb4c32b0ea2	DJANGO	t	2026-06-30 04:16:04.456489+00	2026-06-30 04:16:04.456495+00	b2a7abf6-66a3-4559-9f79-32a7b071aa39	b2a7abf6-66a3-4559-9f79-32a7b071aa39
78395a84-20b5-490d-9b94-8518a2caac26	REACT	t	2026-06-30 04:16:04.457242+00	2026-06-30 04:16:04.457249+00	b2a7abf6-66a3-4559-9f79-32a7b071aa39	b2a7abf6-66a3-4559-9f79-32a7b071aa39
173ac8a8-b787-42f7-837c-a72c435b4f9f	TYPESCRIPT	t	2026-06-30 04:16:04.458011+00	2026-06-30 04:16:04.458017+00	b2a7abf6-66a3-4559-9f79-32a7b071aa39	b2a7abf6-66a3-4559-9f79-32a7b071aa39
16988627-ae7e-45a4-a8c6-f0ef1e022048	POSTGRESQL	t	2026-06-30 04:16:04.458763+00	2026-06-30 04:16:04.45877+00	b2a7abf6-66a3-4559-9f79-32a7b071aa39	b2a7abf6-66a3-4559-9f79-32a7b071aa39
\.


--
-- Data for Name: token_blacklist_blacklistedtoken; Type: TABLE DATA; Schema: public; Owner: luisg
--

COPY public.token_blacklist_blacklistedtoken (id, blacklisted_at, token_id) FROM stdin;
1	2026-06-30 15:18:46.116984+00	3
2	2026-07-06 14:05:38.877708+00	14
3	2026-07-08 23:27:57.424083+00	34
4	2026-07-09 01:34:00.816611+00	36
5	2026-07-09 02:34:22.923583+00	39
\.


--
-- Data for Name: token_blacklist_outstandingtoken; Type: TABLE DATA; Schema: public; Owner: luisg
--

COPY public.token_blacklist_outstandingtoken (id, token, created_at, expires_at, user_id, jti) FROM stdin;
1	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4MjkxMzc5NiwiaWF0IjoxNzgyODI3Mzk2LCJqdGkiOiJiOWZhMDExYWQzMzM0NzQxYjNlOTI2Y2U1NWY4ZjJjNSIsInVzZXJfaWQiOiI2MjgyNjM0NC0zN2YyLTQxNjYtYjhjYi1lYzQyOGI0OWMxMzEifQ.LSyzWBlZRL7UqF27rGb5M3MYUbb11cXJCOjPZv2LgDE	2026-06-30 13:49:56.482281+00	2026-07-01 13:49:56+00	62826344-37f2-4166-b8cb-ec428b49c131	b9fa011ad3334741b3e926ce55f8f2c5
2	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4MzQzMjc4MywiaWF0IjoxNzgyODI3OTgzLCJqdGkiOiJkNDliYzQwMGVjZjA0M2Q5YmVhZTljMGQ2OGVjYjlkMyIsInVzZXJfaWQiOiI2MjgyNjM0NC0zN2YyLTQxNjYtYjhjYi1lYzQyOGI0OWMxMzEifQ.ztOpOwzqr4dBlhdeTKbx_gnRIQ6huXjUC7uzlyOkA0A	2026-06-30 13:59:43.689826+00	2026-07-07 13:59:43+00	62826344-37f2-4166-b8cb-ec428b49c131	d49bc400ecf043d9beae9c0d68ecb9d3
3	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4MzQzMzA4OCwiaWF0IjoxNzgyODI4Mjg4LCJqdGkiOiJlYWE3MDdkMWVkZmI0OGMxOGVlYWYzMmY0NTc0YWZjNCIsInVzZXJfaWQiOiJiN2FlNTgxYi0yZTVhLTQ2MzgtOTA2Zi0yYmM0ZjExNWRjZGUifQ.lXXmrvRTGP66OR4nMNtjXyhAwRwZSwCSYydMxN7HefM	2026-06-30 14:04:48.135168+00	2026-07-07 14:04:48+00	b7ae581b-2e5a-4638-906f-2bc4f115dcde	eaa707d1edfb48c18eeaf32f4574afc4
4	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4MzQzODQ2NSwiaWF0IjoxNzgyODMzNjY1LCJqdGkiOiJhYzM4YmQ4ODU3Zjg0NWY4OWM5MTZlY2UzZjlmYjUzNCIsInVzZXJfaWQiOiJiN2FlNTgxYi0yZTVhLTQ2MzgtOTA2Zi0yYmM0ZjExNWRjZGUifQ.6RdvMYCW77V7tlNJ7Kg0Qb9iC-SwFSja5e1-snCPOnM	2026-06-30 15:34:25.92434+00	2026-07-07 15:34:25+00	b7ae581b-2e5a-4638-906f-2bc4f115dcde	ac38bd8857f845f89c916ece3f9fb534
5	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4MzQzOTIwNSwiaWF0IjoxNzgyODM0NDA1LCJqdGkiOiI0NDNhNDJmMTQxZTg0NThjODQ0NmNiMGI3ODUwZWE4NyIsInVzZXJfaWQiOiJiOTJjNGNjNy1iZTI1LTQwMGYtYmQ5Ni1kNjBhYjFlOGMxODcifQ.hPD-zrlLZ_Rq8dy0kLkBH8wCFsyePEsG8_M9qCeY_9c	2026-06-30 15:46:45.064373+00	2026-07-07 15:46:45+00	b92c4cc7-be25-400f-bd96-d60ab1e8c187	443a42f141e8458c8446cb0b7850ea87
6	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4MzQzOTU0NiwiaWF0IjoxNzgyODM0NzQ2LCJqdGkiOiJkMjVjZDRkMjk3NmQ0N2Q0YTBhYWMxMzIxNjE0NTE0NCIsInVzZXJfaWQiOiI5MTMwMDE0Mi1mODYxLTQwZmYtODkxMC1lNDEzZWQwYzZiNTcifQ.r0lP-KrytWVf9ktm2pAo3x-KBFN85665xU1zhi2hNgk	2026-06-30 15:52:26.519841+00	2026-07-07 15:52:26+00	91300142-f861-40ff-8910-e413ed0c6b57	d25cd4d2976d47d4a0aac13216145144
7	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4MzQzOTk5NSwiaWF0IjoxNzgyODM1MTk1LCJqdGkiOiIzMTRkMDg1OTY4M2Q0MmViYjcxNGQyMmQ3ZjI2ODg5YyIsInVzZXJfaWQiOiI2MjgyNjM0NC0zN2YyLTQxNjYtYjhjYi1lYzQyOGI0OWMxMzEifQ.1LBDD0jTimkzYdsTvfiWog-O_DSXv2J2rH3wtvVDIjI	2026-06-30 15:59:55.907402+00	2026-07-07 15:59:55+00	62826344-37f2-4166-b8cb-ec428b49c131	314d0859683d42ebb714d22d7f26889c
8	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4MzQ0MDEyMywiaWF0IjoxNzgyODM1MzIzLCJqdGkiOiIwMTM4NGIyYThkOGU0NmMyOWViNGU2OTBkYzc4M2ExYiIsInVzZXJfaWQiOiJiN2FlNTgxYi0yZTVhLTQ2MzgtOTA2Zi0yYmM0ZjExNWRjZGUifQ.A-LBTOguSsrZul-vk6wW0Mm5qVO5pwKzTzYExd96skM	2026-06-30 16:02:03.569714+00	2026-07-07 16:02:03+00	b7ae581b-2e5a-4638-906f-2bc4f115dcde	01384b2a8d8e46c29eb4e690dc783a1b
9	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4MzQ4Mzg2MSwiaWF0IjoxNzgyODc5MDYxLCJqdGkiOiJkMjM1ZjU0ZWU2MTc0OTA2YjkzMDU3MWMyOTU0MGQ2ZSIsInVzZXJfaWQiOiJiOTJjNGNjNy1iZTI1LTQwMGYtYmQ5Ni1kNjBhYjFlOGMxODcifQ.6lNOwumEZ44lIjyTdIBpJLagg8vH0M9lu4GMkSv0vGs	2026-07-01 04:11:01.651012+00	2026-07-08 04:11:01+00	b92c4cc7-be25-400f-bd96-d60ab1e8c187	d235f54ee6174906b930571c29540d6e
10	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4MzYzMTU3OSwiaWF0IjoxNzgzMDI2Nzc5LCJqdGkiOiI3ZDJlZjhjYWM4MzY0MTE2ODRlOTlmYzY5NGY5ODg1ZSIsInVzZXJfaWQiOiI5MTMwMDE0Mi1mODYxLTQwZmYtODkxMC1lNDEzZWQwYzZiNTcifQ.grpPII45M3DMwoYL2q4FxxRSjnvtkkKfimrIm52DmMQ	2026-07-02 21:12:59.118787+00	2026-07-09 21:12:59+00	91300142-f861-40ff-8910-e413ed0c6b57	7d2ef8cac836411684e99fc694f9885e
11	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4Mzg5MjIwOCwiaWF0IjoxNzgzMjg3NDA4LCJqdGkiOiIwMTRhNjgzNDg5N2E0NWQ5YmJkY2ZkMjk0NmU2NGU5NyIsInVzZXJfaWQiOiI5MTMwMDE0Mi1mODYxLTQwZmYtODkxMC1lNDEzZWQwYzZiNTcifQ.CXKU6PY-p1JdCEWJVpK3zjSfii8GgbXsHofINJmtszI	2026-07-05 21:36:48.660049+00	2026-07-12 21:36:48+00	91300142-f861-40ff-8910-e413ed0c6b57	014a6834897a45d9bbdcfd2946e64e97
12	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4MzkxNDQyMSwiaWF0IjoxNzgzMzA5NjIxLCJqdGkiOiJjYjQwYjU0NDNjYjM0N2Q1OTdiN2M0YTdkOGRjMjc4MCIsInVzZXJfaWQiOiI2MjgyNjM0NC0zN2YyLTQxNjYtYjhjYi1lYzQyOGI0OWMxMzEifQ.8MCJNcQxsYu4Znd3m-THDMJAOlv3XA6SHOrfNtSJkAE	2026-07-06 03:47:01.521642+00	2026-07-13 03:47:01+00	62826344-37f2-4166-b8cb-ec428b49c131	cb40b5443cb347d597b7c4a7d8dc2780
13	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4MzkxNDQ1NywiaWF0IjoxNzgzMzA5NjU3LCJqdGkiOiI2YzczNWZkNmNiMTE0MmY1YjJjYjRlNmYwYjg2ZDhhMCIsInVzZXJfaWQiOiJiN2FlNTgxYi0yZTVhLTQ2MzgtOTA2Zi0yYmM0ZjExNWRjZGUifQ.4vsmQxr2rg0zUip_g2Q7wczUwkWH91ffQUV421bQilI	2026-07-06 03:47:37.788733+00	2026-07-13 03:47:37+00	b7ae581b-2e5a-4638-906f-2bc4f115dcde	6c735fd6cb1142f5b2cb4e6f0b86d8a0
14	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4Mzk1MTUyNCwiaWF0IjoxNzgzMzQ2NzI0LCJqdGkiOiJjZmFiMWI5MDg0NjI0ZmI5YTYxMmY0OGRkYWUxNWRjMyIsInVzZXJfaWQiOiI2MjgyNjM0NC0zN2YyLTQxNjYtYjhjYi1lYzQyOGI0OWMxMzEifQ.7XjW_kkx1-yg6VGQxCWoJxZDwg9nwyjf1_HQPFtSs2w	2026-07-06 14:05:24.439237+00	2026-07-13 14:05:24+00	62826344-37f2-4166-b8cb-ec428b49c131	cfab1b9084624fb9a612f48ddae15dc3
15	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4Mzk3MzU0NiwiaWF0IjoxNzgzMzY4NzQ2LCJqdGkiOiJiZWQ0MjQ5YTQwN2I0ODk5YjgxNmI0Njc0NmIyZGU0OCIsInVzZXJfaWQiOiI2MjgyNjM0NC0zN2YyLTQxNjYtYjhjYi1lYzQyOGI0OWMxMzEifQ.q0T0LWApMj6QtA_r7V_ejylPRokNWQJC5LyP_bHm3u8	2026-07-06 20:12:26.079497+00	2026-07-13 20:12:26+00	62826344-37f2-4166-b8cb-ec428b49c131	bed4249a407b4899b816b46746b2de48
16	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4Mzk3NTk3MywiaWF0IjoxNzgzMzcxMTczLCJqdGkiOiI3ZDdmMzU5NzMxZTk0MDcwODQ5Y2Q5NTQyZWIyOWU0MiIsInVzZXJfaWQiOiJiN2FlNTgxYi0yZTVhLTQ2MzgtOTA2Zi0yYmM0ZjExNWRjZGUifQ.dD2mx7yAbDgT3WURgf2P5q-iSnzNNk1goqDLFJqvR5Y	2026-07-06 20:52:53.084612+00	2026-07-13 20:52:53+00	b7ae581b-2e5a-4638-906f-2bc4f115dcde	7d7f359731e94070849cd9542eb29e42
17	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4Mzk3NjA4MCwiaWF0IjoxNzgzMzcxMjgwLCJqdGkiOiIwMjg4MDU4ZjU4OGI0MzViYmM5YjBmZjg4ZmU3ZWY5YiIsInVzZXJfaWQiOiJiOTJjNGNjNy1iZTI1LTQwMGYtYmQ5Ni1kNjBhYjFlOGMxODcifQ.hUAda3nNJSd9Hs5rMFh0eV0-BJtQjmpUqNsAnJo3XFg	2026-07-06 20:54:40.764917+00	2026-07-13 20:54:40+00	b92c4cc7-be25-400f-bd96-d60ab1e8c187	0288058f588b435bbc9b0ff88fe7ef9b
18	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4Mzk3NjE0OCwiaWF0IjoxNzgzMzcxMzQ4LCJqdGkiOiIyZTk5MGJlMGViMWE0M2RiOTI2MDZlYTg0NjY1M2RmNyIsInVzZXJfaWQiOiI5MTMwMDE0Mi1mODYxLTQwZmYtODkxMC1lNDEzZWQwYzZiNTcifQ.kMMPSFVpnDkKbNm9dOIAxEtLeFN8Z9BDsa24PJB-s44	2026-07-06 20:55:48.136673+00	2026-07-13 20:55:48+00	91300142-f861-40ff-8910-e413ed0c6b57	2e990be0eb1a43db92606ea846653df7
19	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4NDE0NTM1NywiaWF0IjoxNzgzNTQwNTU3LCJqdGkiOiIzODdjYzQ0NDlkYTI0MGI2YTkwODg2NzRmMzVjYzdiMCIsInVzZXJfaWQiOiI2MjgyNjM0NC0zN2YyLTQxNjYtYjhjYi1lYzQyOGI0OWMxMzEifQ.6iyvcrV__l0X9jSyzjsjKiOdEFWSz_8k01nSdpwRzhY	2026-07-08 19:55:57.092231+00	2026-07-15 19:55:57+00	62826344-37f2-4166-b8cb-ec428b49c131	387cc4449da240b6a9088674f35cc7b0
20	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4NDE1MDk4OSwiaWF0IjoxNzgzNTQ2MTg5LCJqdGkiOiI4YTRjZjczOWU3YjY0MjQ4YmQ0NDE3MjI2NjAxNzdlMyIsInVzZXJfaWQiOiI2MjgyNjM0NC0zN2YyLTQxNjYtYjhjYi1lYzQyOGI0OWMxMzEifQ.cThXmbqaXhEHGkbasH2v6MoqmQoNlSL2IFayY2Gyknk	2026-07-08 21:29:49.226628+00	2026-07-15 21:29:49+00	62826344-37f2-4166-b8cb-ec428b49c131	8a4cf739e7b64248bd441722660177e3
21	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4NDE1MTE0MSwiaWF0IjoxNzgzNTQ2MzQxLCJqdGkiOiJhNGQ4OTRhMzE3ZGE0NWM2YTVmZDBlMWU4MDU5YWY5ZCIsInVzZXJfaWQiOiI2MjgyNjM0NC0zN2YyLTQxNjYtYjhjYi1lYzQyOGI0OWMxMzEifQ.vJoVUvDWNaXWxVeL8BEwOAk8vR-iFSVaUt76TmWIkRY	2026-07-08 21:32:21.767367+00	2026-07-15 21:32:21+00	62826344-37f2-4166-b8cb-ec428b49c131	a4d894a317da45c6a5fd0e1e8059af9d
22	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4NDE1MTMxNSwiaWF0IjoxNzgzNTQ2NTE1LCJqdGkiOiI4YmQzOGM3MWY0MzU0YzYwYTBmYTdhYzY4MjhkZDg0ZiIsInVzZXJfaWQiOiI2MjgyNjM0NC0zN2YyLTQxNjYtYjhjYi1lYzQyOGI0OWMxMzEifQ.Or2KHU40aGlMAyad7QTYQqnvZyLZzD1R1LVJu_2QtLE	2026-07-08 21:35:15.033468+00	2026-07-15 21:35:15+00	62826344-37f2-4166-b8cb-ec428b49c131	8bd38c71f4354c60a0fa7ac6828dd84f
23	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4NDE1MTM0OSwiaWF0IjoxNzgzNTQ2NTQ5LCJqdGkiOiI2OTJiMDExZTUzZWU0MDA1YjQ3MTEyZjU2NTU5YjMyYSIsInVzZXJfaWQiOiI2MjgyNjM0NC0zN2YyLTQxNjYtYjhjYi1lYzQyOGI0OWMxMzEifQ.4DwtCVmOV_kI2rb0uYkK6-cs0db8ezjM_9uNatApTWM	2026-07-08 21:35:49.576655+00	2026-07-15 21:35:49+00	62826344-37f2-4166-b8cb-ec428b49c131	692b011e53ee4005b47112f56559b32a
24	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4NDE1MjQxMCwiaWF0IjoxNzgzNTQ3NjEwLCJqdGkiOiJiNzgwYzY5ZmRjNzc0MTY5OWNhNjMzNjE0MjMzMmEyOCIsInVzZXJfaWQiOiI2MjgyNjM0NC0zN2YyLTQxNjYtYjhjYi1lYzQyOGI0OWMxMzEifQ.gsEWMiuiECN1CdLts9JoztwyY1Pz9By7Yvu-xudnrAo	2026-07-08 21:53:30.648472+00	2026-07-15 21:53:30+00	62826344-37f2-4166-b8cb-ec428b49c131	b780c69fdc7741699ca6336142332a28
25	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4NDE1MjU0OCwiaWF0IjoxNzgzNTQ3NzQ4LCJqdGkiOiJhMDNhZDYyMGVkNTE0Yzc1YmMwYTlkMWYxMDhmY2U0NiIsInVzZXJfaWQiOiI2MjgyNjM0NC0zN2YyLTQxNjYtYjhjYi1lYzQyOGI0OWMxMzEifQ.kWS8FRFYQRy6QGFzxtrQuK8DV-7dDS9xybZ0P7fzOqI	2026-07-08 21:55:48.137636+00	2026-07-15 21:55:48+00	62826344-37f2-4166-b8cb-ec428b49c131	a03ad620ed514c75bc0a9d1f108fce46
26	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4NDE1MjYzMCwiaWF0IjoxNzgzNTQ3ODMwLCJqdGkiOiJkMTBkZDQ4YWM4YjU0NjM0YmI4M2E2MzAwNzFhMjE0ZSIsInVzZXJfaWQiOiI2MjgyNjM0NC0zN2YyLTQxNjYtYjhjYi1lYzQyOGI0OWMxMzEifQ.4t7pBYcqroAv0i1IeuWiUYidDwoo43CPMtRepTBgWk4	2026-07-08 21:57:10.222509+00	2026-07-15 21:57:10+00	62826344-37f2-4166-b8cb-ec428b49c131	d10dd48ac8b54634bb83a630071a214e
27	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4NDE1Mjc0MiwiaWF0IjoxNzgzNTQ3OTQyLCJqdGkiOiI0M2E5M2U4YmQyYWE0NzhmOWQyY2FhYTRmMzc3ZjQwZSIsInVzZXJfaWQiOiI2MjgyNjM0NC0zN2YyLTQxNjYtYjhjYi1lYzQyOGI0OWMxMzEifQ.-9hvribcmWvbRB8RqJ4Gy3SreSo5xP6_yIn0A0jmtNk	2026-07-08 21:59:02.014668+00	2026-07-15 21:59:02+00	62826344-37f2-4166-b8cb-ec428b49c131	43a93e8bd2aa478f9d2caaa4f377f40e
28	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4NDE1Mjg1NSwiaWF0IjoxNzgzNTQ4MDU1LCJqdGkiOiI2NDZkOTk1ZmRlZjg0YzQzOWY3NDU3ZWVhMDczOTNmYyIsInVzZXJfaWQiOiI2MjgyNjM0NC0zN2YyLTQxNjYtYjhjYi1lYzQyOGI0OWMxMzEifQ.U9UMaeDckURu7igZoQqYXG-V2rF5APKkIMrzNgsAwWQ	2026-07-08 22:00:55.140403+00	2026-07-15 22:00:55+00	62826344-37f2-4166-b8cb-ec428b49c131	646d995fdef84c439f7457eea07393fc
29	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4NDE1Mjg4NiwiaWF0IjoxNzgzNTQ4MDg2LCJqdGkiOiI2ZmQ3NjAyNTUyY2I0MDVkYmVmYTQyMzBhMmRkMTdmNSIsInVzZXJfaWQiOiI2MjgyNjM0NC0zN2YyLTQxNjYtYjhjYi1lYzQyOGI0OWMxMzEifQ.UvGvVMvpJ9QMozsi1OvjzBukpbq_5ETNzYt_BVTbtjo	2026-07-08 22:01:26.080695+00	2026-07-15 22:01:26+00	62826344-37f2-4166-b8cb-ec428b49c131	6fd7602552cb405dbefa4230a2dd17f5
30	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4NDE1Mjk5MCwiaWF0IjoxNzgzNTQ4MTkwLCJqdGkiOiIzNjRiZGE0MjM2NTM0YmI5ODEyZmRlMmJlOTIxNWE2OSIsInVzZXJfaWQiOiI2MjgyNjM0NC0zN2YyLTQxNjYtYjhjYi1lYzQyOGI0OWMxMzEifQ.M-KHN9xhPEanO_OiGMFF3SIL_EJD63ikCsMmHhcuL8g	2026-07-08 22:03:10.654419+00	2026-07-15 22:03:10+00	62826344-37f2-4166-b8cb-ec428b49c131	364bda4236534bb9812fde2be9215a69
31	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4NDE1MzAzNiwiaWF0IjoxNzgzNTQ4MjM2LCJqdGkiOiIxN2M5ZGFlNzAyNmQ0NTg0OTg1M2NlZGYwNTA5ZjM4ZCIsInVzZXJfaWQiOiI2MjgyNjM0NC0zN2YyLTQxNjYtYjhjYi1lYzQyOGI0OWMxMzEifQ.QMzeg86N8Ykyxz2IplU3GqY7BwNxStNUZ8RIRsa53QE	2026-07-08 22:03:56.101287+00	2026-07-15 22:03:56+00	62826344-37f2-4166-b8cb-ec428b49c131	17c9dae7026d45849853cedf0509f38d
32	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4NDE1MzE5MSwiaWF0IjoxNzgzNTQ4MzkxLCJqdGkiOiI0NWE0OGFiZTBlNDQ0MDJmOWFjMDc2MTllYWZmYjA4YiIsInVzZXJfaWQiOiI2MjgyNjM0NC0zN2YyLTQxNjYtYjhjYi1lYzQyOGI0OWMxMzEifQ.jbDpXtSbcfmw65UJGnJLU6YNAOt8bteGn3X4q7HJ3DE	2026-07-08 22:06:31.21276+00	2026-07-15 22:06:31+00	62826344-37f2-4166-b8cb-ec428b49c131	45a48abe0e44402f9ac07619eaffb08b
33	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4NDE1NDA0NywiaWF0IjoxNzgzNTQ5MjQ3LCJqdGkiOiJhZTNkYjY0YzEyZmM0NzU5YjFmZTYxYzJiMjI1OTFiOSIsInVzZXJfaWQiOiI2MjgyNjM0NC0zN2YyLTQxNjYtYjhjYi1lYzQyOGI0OWMxMzEifQ.Ud2lCVVqeW7FiHyrcWVijCyQ8e_IQYWeSyY6VrTin24	2026-07-08 22:20:47.906363+00	2026-07-15 22:20:47+00	62826344-37f2-4166-b8cb-ec428b49c131	ae3db64c12fc4759b1fe61c2b22591b9
34	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4NDE1NDQ3MywiaWF0IjoxNzgzNTQ5NjczLCJqdGkiOiIxMWNkODU5YzdiYWE0OTc2OWQ1ZTQ5MTU1YTBhZDBlYiIsInVzZXJfaWQiOiI2MjgyNjM0NC0zN2YyLTQxNjYtYjhjYi1lYzQyOGI0OWMxMzEifQ.kMwwTrpir2jZoYvOSUZbckLhgGBAYxzHXsh65_bN-W8	2026-07-08 22:27:53.222087+00	2026-07-15 22:27:53+00	62826344-37f2-4166-b8cb-ec428b49c131	11cd859c7baa49769d5e49155a0ad0eb
35	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4NDE2MTU1NiwiaWF0IjoxNzgzNTU2NzU2LCJqdGkiOiI1ZDc4NmYxNGUxYjE0NmNhYTY4OGFiODcxZjczMzY1YSIsInVzZXJfaWQiOiI2MjgyNjM0NC0zN2YyLTQxNjYtYjhjYi1lYzQyOGI0OWMxMzEifQ.8_5fAaU0snQ72Gv9ezLFEg5bWRNje6A716zmBfB7SD8	2026-07-09 00:25:56.91419+00	2026-07-16 00:25:56+00	62826344-37f2-4166-b8cb-ec428b49c131	5d786f14e1b146caa688ab871f73365a
36	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4NDE2MTYzNSwiaWF0IjoxNzgzNTU2ODM1LCJqdGkiOiIxMzlhZDEyYjczZjA0NDhlYWFhMWRhOTU4OTRkZGQ4NyIsInVzZXJfaWQiOiI2MjgyNjM0NC0zN2YyLTQxNjYtYjhjYi1lYzQyOGI0OWMxMzEifQ.AJRr5nMuu8X1cm92hS9oRu9ENuj8BvlCuoRXhofaCbw	2026-07-09 00:27:15.20649+00	2026-07-16 00:27:15+00	62826344-37f2-4166-b8cb-ec428b49c131	139ad12b73f0448eaaa1da95894ddd87
37	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4NDE2NjAxNywiaWF0IjoxNzgzNTYxMjE3LCJqdGkiOiJiNDgyOGUxMGVlZDg0M2E0YmJiZWM4NjYzNTFjZDAxYSIsInVzZXJfaWQiOiI2MjgyNjM0NC0zN2YyLTQxNjYtYjhjYi1lYzQyOGI0OWMxMzEifQ.-0ZzhUR4zaSIj_rQik7rlYjvKwhgxcM_PKR1qK3DPp4	2026-07-09 01:40:17.539355+00	2026-07-16 01:40:17+00	62826344-37f2-4166-b8cb-ec428b49c131	b4828e10eed843a4bbbec866351cd01a
38	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4NDE2Nzc3MywiaWF0IjoxNzgzNTYyOTczLCJqdGkiOiI1MDUyOGI3M2FkZTk0NmZjYjk1MjI4ODM3MTY2NGE0MSIsInVzZXJfaWQiOiI2MjgyNjM0NC0zN2YyLTQxNjYtYjhjYi1lYzQyOGI0OWMxMzEifQ.qb4YMv4CC-IywQL6lWkK7zgJeSOFzdKm3gMNFGfm0TQ	2026-07-09 02:09:33.867742+00	2026-07-16 02:09:33+00	62826344-37f2-4166-b8cb-ec428b49c131	50528b73ade946fcb952288371664a41
39	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4NDE2NTY0MCwiaWF0IjoxNzgzNTYwODQwLCJqdGkiOiIzNmFiNzgzZjdjOWE0OWE5OTY4NzI3Y2MzMGE2ZGY4OCIsInVzZXJfaWQiOiI2MjgyNjM0NC0zN2YyLTQxNjYtYjhjYi1lYzQyOGI0OWMxMzEifQ.0azrPMUp4kD0UH3ZGlYFoa0nXhzgnNblGPEqHUtODto	\N	2026-07-16 01:34:00+00	\N	36ab783f7c9a49a9968727cc30a6df88
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: luisg
--

COPY public.users (password, last_login, is_superuser, username, email, is_staff, is_active, date_joined, first_name, last_name, id, modified, creator_id, modifier_id) FROM stdin;
pbkdf2_sha256$1000000$TUVr6BszshgWnRxokBcfhG$dgpA2cVaYD5vnQnJgfQyjX2fWBgCReWjeq8cZlnMW9I=	\N	t	luisg	luisgardaz13@gmail.com	t	t	2026-06-30 04:16:04.320959+00			b2a7abf6-66a3-4559-9f79-32a7b071aa39	2026-06-30 04:16:04.442979+00	b2a7abf6-66a3-4559-9f79-32a7b071aa39	b2a7abf6-66a3-4559-9f79-32a7b071aa39
pbkdf2_sha256$1000000$X85lQ1hnOpKVGULpXwT3ck$c68tvEgBU/li9G89WXp/9Nk97C7Y5WLYfHGznz7/BOs=	\N	f	jose_gimenez	jose@gmail.com	f	t	2026-06-30 13:48:18.699982+00	JOSE	GIMENEZ	62826344-37f2-4166-b8cb-ec428b49c131	2026-06-30 13:48:18.829908+00	62826344-37f2-4166-b8cb-ec428b49c131	62826344-37f2-4166-b8cb-ec428b49c131
pbkdf2_sha256$1000000$3j4XPoXb7JsqNQrzmOMNRf$IT1Y86n+FsLrlkB39B0QbZgvMaKbM6cpmfKGfM7bovw=	\N	f	lucia_apaza	lucia@gmail.com	f	t	2026-06-30 14:04:14.152587+00	LUCIA	APAZA	b7ae581b-2e5a-4638-906f-2bc4f115dcde	2026-06-30 14:04:14.282482+00	b7ae581b-2e5a-4638-906f-2bc4f115dcde	b7ae581b-2e5a-4638-906f-2bc4f115dcde
pbkdf2_sha256$1000000$4iGZWee8351R7xz1K52lqE$8QZeIToETLQm+ZnKTi8KdofvGsZU+VCJ6bU72MIAkAo=	\N	f	maria_rodriguez	maria@gmail.com	f	t	2026-06-30 15:46:20.26775+00	MARIA	RODRIGUEZ	b92c4cc7-be25-400f-bd96-d60ab1e8c187	2026-06-30 15:46:20.401068+00	b92c4cc7-be25-400f-bd96-d60ab1e8c187	b92c4cc7-be25-400f-bd96-d60ab1e8c187
pbkdf2_sha256$1000000$ht1TN2T9hAsfhjT81BWi3O$0sqqAlf28Ij4dXPq4v+49I/MLSXCVO7lq4QriFhjDWo=	\N	f	carlos_perez	carlos@gmail.com	f	t	2026-06-30 15:51:56.190257+00	CARLOS	PEREZ	91300142-f861-40ff-8910-e413ed0c6b57	2026-06-30 15:51:56.332059+00	91300142-f861-40ff-8910-e413ed0c6b57	91300142-f861-40ff-8910-e413ed0c6b57
\.


--
-- Data for Name: users_groups; Type: TABLE DATA; Schema: public; Owner: luisg
--

COPY public.users_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: users_user_permissions; Type: TABLE DATA; Schema: public; Owner: luisg
--

COPY public.users_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: luisg
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: luisg
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: luisg
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 64, true);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: luisg
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, false);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: luisg
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 16, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: luisg
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 31, true);


--
-- Name: token_blacklist_blacklistedtoken_id_seq; Type: SEQUENCE SET; Schema: public; Owner: luisg
--

SELECT pg_catalog.setval('public.token_blacklist_blacklistedtoken_id_seq', 5, true);


--
-- Name: token_blacklist_outstandingtoken_id_seq; Type: SEQUENCE SET; Schema: public; Owner: luisg
--

SELECT pg_catalog.setval('public.token_blacklist_outstandingtoken_id_seq', 39, true);


--
-- Name: users_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: luisg
--

SELECT pg_catalog.setval('public.users_groups_id_seq', 1, false);


--
-- Name: users_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: luisg
--

SELECT pg_catalog.setval('public.users_user_permissions_id_seq', 1, false);


--
-- Name: applications applications_pkey; Type: CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.applications
    ADD CONSTRAINT applications_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: candidates candidates_pkey; Type: CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.candidates
    ADD CONSTRAINT candidates_pkey PRIMARY KEY (id);


--
-- Name: candidates candidates_user_id_key; Type: CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.candidates
    ADD CONSTRAINT candidates_user_id_key UNIQUE (user_id);


--
-- Name: companies companies_pkey; Type: CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.companies
    ADD CONSTRAINT companies_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: locations locations_name_key; Type: CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.locations
    ADD CONSTRAINT locations_name_key UNIQUE (name);


--
-- Name: locations locations_pkey; Type: CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.locations
    ADD CONSTRAINT locations_pkey PRIMARY KEY (id);


--
-- Name: offers offers_pkey; Type: CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.offers
    ADD CONSTRAINT offers_pkey PRIMARY KEY (id);


--
-- Name: offers_technologies offers_technologies_pkey; Type: CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.offers_technologies
    ADD CONSTRAINT offers_technologies_pkey PRIMARY KEY (id);


--
-- Name: recruiters recruiters_pkey; Type: CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.recruiters
    ADD CONSTRAINT recruiters_pkey PRIMARY KEY (id);


--
-- Name: recruiters recruiters_user_id_key; Type: CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.recruiters
    ADD CONSTRAINT recruiters_user_id_key UNIQUE (user_id);


--
-- Name: technologies technologies_name_key; Type: CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.technologies
    ADD CONSTRAINT technologies_name_key UNIQUE (name);


--
-- Name: technologies technologies_pkey; Type: CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.technologies
    ADD CONSTRAINT technologies_pkey PRIMARY KEY (id);


--
-- Name: token_blacklist_blacklistedtoken token_blacklist_blacklistedtoken_pkey; Type: CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.token_blacklist_blacklistedtoken
    ADD CONSTRAINT token_blacklist_blacklistedtoken_pkey PRIMARY KEY (id);


--
-- Name: token_blacklist_blacklistedtoken token_blacklist_blacklistedtoken_token_id_key; Type: CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.token_blacklist_blacklistedtoken
    ADD CONSTRAINT token_blacklist_blacklistedtoken_token_id_key UNIQUE (token_id);


--
-- Name: token_blacklist_outstandingtoken token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_uniq; Type: CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.token_blacklist_outstandingtoken
    ADD CONSTRAINT token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_uniq UNIQUE (jti);


--
-- Name: token_blacklist_outstandingtoken token_blacklist_outstandingtoken_pkey; Type: CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.token_blacklist_outstandingtoken
    ADD CONSTRAINT token_blacklist_outstandingtoken_pkey PRIMARY KEY (id);


--
-- Name: users_groups users_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.users_groups
    ADD CONSTRAINT users_groups_pkey PRIMARY KEY (id);


--
-- Name: users_groups users_groups_user_id_group_id_fc7788e8_uniq; Type: CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.users_groups
    ADD CONSTRAINT users_groups_user_id_group_id_fc7788e8_uniq UNIQUE (user_id, group_id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: users_user_permissions users_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.users_user_permissions
    ADD CONSTRAINT users_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: users_user_permissions users_user_permissions_user_id_permission_id_3b86cbdf_uniq; Type: CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.users_user_permissions
    ADD CONSTRAINT users_user_permissions_user_id_permission_id_3b86cbdf_uniq UNIQUE (user_id, permission_id);


--
-- Name: users users_username_key; Type: CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_username_key UNIQUE (username);


--
-- Name: applications_candidate_id_f90db3c6; Type: INDEX; Schema: public; Owner: luisg
--

CREATE INDEX applications_candidate_id_f90db3c6 ON public.applications USING btree (candidate_id);


--
-- Name: applications_creator_id_686cec4b; Type: INDEX; Schema: public; Owner: luisg
--

CREATE INDEX applications_creator_id_686cec4b ON public.applications USING btree (creator_id);


--
-- Name: applications_modifier_id_2b36e80e; Type: INDEX; Schema: public; Owner: luisg
--

CREATE INDEX applications_modifier_id_2b36e80e ON public.applications USING btree (modifier_id);


--
-- Name: applications_offer_id_82d40565; Type: INDEX; Schema: public; Owner: luisg
--

CREATE INDEX applications_offer_id_82d40565 ON public.applications USING btree (offer_id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: luisg
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: luisg
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: luisg
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: luisg
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: candidates_creator_id_de0c3f46; Type: INDEX; Schema: public; Owner: luisg
--

CREATE INDEX candidates_creator_id_de0c3f46 ON public.candidates USING btree (creator_id);


--
-- Name: candidates_modifier_id_16ff9fb3; Type: INDEX; Schema: public; Owner: luisg
--

CREATE INDEX candidates_modifier_id_16ff9fb3 ON public.candidates USING btree (modifier_id);


--
-- Name: companies_creator_id_458fd19b; Type: INDEX; Schema: public; Owner: luisg
--

CREATE INDEX companies_creator_id_458fd19b ON public.companies USING btree (creator_id);


--
-- Name: companies_modifier_id_4fed516d; Type: INDEX; Schema: public; Owner: luisg
--

CREATE INDEX companies_modifier_id_4fed516d ON public.companies USING btree (modifier_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: luisg
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: luisg
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: luisg
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: luisg
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: idx_user_full_name; Type: INDEX; Schema: public; Owner: luisg
--

CREATE INDEX idx_user_full_name ON public.users USING btree (first_name, last_name);


--
-- Name: locations_creator_id_8874d202; Type: INDEX; Schema: public; Owner: luisg
--

CREATE INDEX locations_creator_id_8874d202 ON public.locations USING btree (creator_id);


--
-- Name: locations_modifier_id_8af9e79a; Type: INDEX; Schema: public; Owner: luisg
--

CREATE INDEX locations_modifier_id_8af9e79a ON public.locations USING btree (modifier_id);


--
-- Name: locations_name_512a106e_like; Type: INDEX; Schema: public; Owner: luisg
--

CREATE INDEX locations_name_512a106e_like ON public.locations USING btree (name varchar_pattern_ops);


--
-- Name: offers_creator_id_9bf8c888; Type: INDEX; Schema: public; Owner: luisg
--

CREATE INDEX offers_creator_id_9bf8c888 ON public.offers USING btree (creator_id);


--
-- Name: offers_location_id_949e7bb5; Type: INDEX; Schema: public; Owner: luisg
--

CREATE INDEX offers_location_id_949e7bb5 ON public.offers USING btree (location_id);


--
-- Name: offers_modifier_id_f0aa9d0f; Type: INDEX; Schema: public; Owner: luisg
--

CREATE INDEX offers_modifier_id_f0aa9d0f ON public.offers USING btree (modifier_id);


--
-- Name: offers_recruiter_id_73e30ceb; Type: INDEX; Schema: public; Owner: luisg
--

CREATE INDEX offers_recruiter_id_73e30ceb ON public.offers USING btree (recruiter_id);


--
-- Name: offers_technologies_offer_id_b96d39e9; Type: INDEX; Schema: public; Owner: luisg
--

CREATE INDEX offers_technologies_offer_id_b96d39e9 ON public.offers_technologies USING btree (offer_id);


--
-- Name: offers_technologies_technology_id_9bb12fae; Type: INDEX; Schema: public; Owner: luisg
--

CREATE INDEX offers_technologies_technology_id_9bb12fae ON public.offers_technologies USING btree (technology_id);


--
-- Name: recruiters_company_id_4654a403; Type: INDEX; Schema: public; Owner: luisg
--

CREATE INDEX recruiters_company_id_4654a403 ON public.recruiters USING btree (company_id);


--
-- Name: recruiters_creator_id_e98d4e08; Type: INDEX; Schema: public; Owner: luisg
--

CREATE INDEX recruiters_creator_id_e98d4e08 ON public.recruiters USING btree (creator_id);


--
-- Name: recruiters_modifier_id_b4be1559; Type: INDEX; Schema: public; Owner: luisg
--

CREATE INDEX recruiters_modifier_id_b4be1559 ON public.recruiters USING btree (modifier_id);


--
-- Name: technologies_creator_id_ae983019; Type: INDEX; Schema: public; Owner: luisg
--

CREATE INDEX technologies_creator_id_ae983019 ON public.technologies USING btree (creator_id);


--
-- Name: technologies_modifier_id_b92b78af; Type: INDEX; Schema: public; Owner: luisg
--

CREATE INDEX technologies_modifier_id_b92b78af ON public.technologies USING btree (modifier_id);


--
-- Name: technologies_name_21c5c2f9_like; Type: INDEX; Schema: public; Owner: luisg
--

CREATE INDEX technologies_name_21c5c2f9_like ON public.technologies USING btree (name varchar_pattern_ops);


--
-- Name: token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_like; Type: INDEX; Schema: public; Owner: luisg
--

CREATE INDEX token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_like ON public.token_blacklist_outstandingtoken USING btree (jti varchar_pattern_ops);


--
-- Name: token_blacklist_outstandingtoken_user_id_83bc629a; Type: INDEX; Schema: public; Owner: luisg
--

CREATE INDEX token_blacklist_outstandingtoken_user_id_83bc629a ON public.token_blacklist_outstandingtoken USING btree (user_id);


--
-- Name: users_creator_id_05421e81; Type: INDEX; Schema: public; Owner: luisg
--

CREATE INDEX users_creator_id_05421e81 ON public.users USING btree (creator_id);


--
-- Name: users_groups_group_id_2f3517aa; Type: INDEX; Schema: public; Owner: luisg
--

CREATE INDEX users_groups_group_id_2f3517aa ON public.users_groups USING btree (group_id);


--
-- Name: users_groups_user_id_f500bee5; Type: INDEX; Schema: public; Owner: luisg
--

CREATE INDEX users_groups_user_id_f500bee5 ON public.users_groups USING btree (user_id);


--
-- Name: users_modifier_id_60df99e1; Type: INDEX; Schema: public; Owner: luisg
--

CREATE INDEX users_modifier_id_60df99e1 ON public.users USING btree (modifier_id);


--
-- Name: users_user_permissions_permission_id_6d08dcd2; Type: INDEX; Schema: public; Owner: luisg
--

CREATE INDEX users_user_permissions_permission_id_6d08dcd2 ON public.users_user_permissions USING btree (permission_id);


--
-- Name: users_user_permissions_user_id_92473840; Type: INDEX; Schema: public; Owner: luisg
--

CREATE INDEX users_user_permissions_user_id_92473840 ON public.users_user_permissions USING btree (user_id);


--
-- Name: users_username_e8658fc8_like; Type: INDEX; Schema: public; Owner: luisg
--

CREATE INDEX users_username_e8658fc8_like ON public.users USING btree (username varchar_pattern_ops);


--
-- Name: applications applications_candidate_id_f90db3c6_fk_candidates_id; Type: FK CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.applications
    ADD CONSTRAINT applications_candidate_id_f90db3c6_fk_candidates_id FOREIGN KEY (candidate_id) REFERENCES public.candidates(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: applications applications_creator_id_686cec4b_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.applications
    ADD CONSTRAINT applications_creator_id_686cec4b_fk_users_id FOREIGN KEY (creator_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: applications applications_modifier_id_2b36e80e_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.applications
    ADD CONSTRAINT applications_modifier_id_2b36e80e_fk_users_id FOREIGN KEY (modifier_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: applications applications_offer_id_82d40565_fk_offers_id; Type: FK CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.applications
    ADD CONSTRAINT applications_offer_id_82d40565_fk_offers_id FOREIGN KEY (offer_id) REFERENCES public.offers(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: candidates candidates_creator_id_de0c3f46_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.candidates
    ADD CONSTRAINT candidates_creator_id_de0c3f46_fk_users_id FOREIGN KEY (creator_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: candidates candidates_modifier_id_16ff9fb3_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.candidates
    ADD CONSTRAINT candidates_modifier_id_16ff9fb3_fk_users_id FOREIGN KEY (modifier_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: candidates candidates_user_id_38b3e027_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.candidates
    ADD CONSTRAINT candidates_user_id_38b3e027_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: companies companies_creator_id_458fd19b_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.companies
    ADD CONSTRAINT companies_creator_id_458fd19b_fk_users_id FOREIGN KEY (creator_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: companies companies_modifier_id_4fed516d_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.companies
    ADD CONSTRAINT companies_modifier_id_4fed516d_fk_users_id FOREIGN KEY (modifier_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: locations locations_creator_id_8874d202_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.locations
    ADD CONSTRAINT locations_creator_id_8874d202_fk_users_id FOREIGN KEY (creator_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: locations locations_modifier_id_8af9e79a_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.locations
    ADD CONSTRAINT locations_modifier_id_8af9e79a_fk_users_id FOREIGN KEY (modifier_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: offers offers_creator_id_9bf8c888_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.offers
    ADD CONSTRAINT offers_creator_id_9bf8c888_fk_users_id FOREIGN KEY (creator_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: offers offers_location_id_949e7bb5_fk_locations_id; Type: FK CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.offers
    ADD CONSTRAINT offers_location_id_949e7bb5_fk_locations_id FOREIGN KEY (location_id) REFERENCES public.locations(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: offers offers_modifier_id_f0aa9d0f_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.offers
    ADD CONSTRAINT offers_modifier_id_f0aa9d0f_fk_users_id FOREIGN KEY (modifier_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: offers offers_recruiter_id_73e30ceb_fk_recruiters_id; Type: FK CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.offers
    ADD CONSTRAINT offers_recruiter_id_73e30ceb_fk_recruiters_id FOREIGN KEY (recruiter_id) REFERENCES public.recruiters(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: offers_technologies offers_technologies_offer_id_b96d39e9_fk_offers_id; Type: FK CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.offers_technologies
    ADD CONSTRAINT offers_technologies_offer_id_b96d39e9_fk_offers_id FOREIGN KEY (offer_id) REFERENCES public.offers(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: offers_technologies offers_technologies_technology_id_9bb12fae_fk_technologies_id; Type: FK CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.offers_technologies
    ADD CONSTRAINT offers_technologies_technology_id_9bb12fae_fk_technologies_id FOREIGN KEY (technology_id) REFERENCES public.technologies(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: recruiters recruiters_company_id_4654a403_fk_companies_id; Type: FK CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.recruiters
    ADD CONSTRAINT recruiters_company_id_4654a403_fk_companies_id FOREIGN KEY (company_id) REFERENCES public.companies(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: recruiters recruiters_creator_id_e98d4e08_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.recruiters
    ADD CONSTRAINT recruiters_creator_id_e98d4e08_fk_users_id FOREIGN KEY (creator_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: recruiters recruiters_modifier_id_b4be1559_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.recruiters
    ADD CONSTRAINT recruiters_modifier_id_b4be1559_fk_users_id FOREIGN KEY (modifier_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: recruiters recruiters_user_id_50c8b723_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.recruiters
    ADD CONSTRAINT recruiters_user_id_50c8b723_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: technologies technologies_creator_id_ae983019_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.technologies
    ADD CONSTRAINT technologies_creator_id_ae983019_fk_users_id FOREIGN KEY (creator_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: technologies technologies_modifier_id_b92b78af_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.technologies
    ADD CONSTRAINT technologies_modifier_id_b92b78af_fk_users_id FOREIGN KEY (modifier_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: token_blacklist_blacklistedtoken token_blacklist_blacklistedtoken_token_id_3cc7fe56_fk; Type: FK CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.token_blacklist_blacklistedtoken
    ADD CONSTRAINT token_blacklist_blacklistedtoken_token_id_3cc7fe56_fk FOREIGN KEY (token_id) REFERENCES public.token_blacklist_outstandingtoken(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: token_blacklist_outstandingtoken token_blacklist_outstandingtoken_user_id_83bc629a_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.token_blacklist_outstandingtoken
    ADD CONSTRAINT token_blacklist_outstandingtoken_user_id_83bc629a_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users users_creator_id_05421e81_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_creator_id_05421e81_fk_users_id FOREIGN KEY (creator_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_groups users_groups_group_id_2f3517aa_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.users_groups
    ADD CONSTRAINT users_groups_group_id_2f3517aa_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_groups users_groups_user_id_f500bee5_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.users_groups
    ADD CONSTRAINT users_groups_user_id_f500bee5_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users users_modifier_id_60df99e1_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_modifier_id_60df99e1_fk_users_id FOREIGN KEY (modifier_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_permissions users_user_permissio_permission_id_6d08dcd2_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.users_user_permissions
    ADD CONSTRAINT users_user_permissio_permission_id_6d08dcd2_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_permissions users_user_permissions_user_id_92473840_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: luisg
--

ALTER TABLE ONLY public.users_user_permissions
    ADD CONSTRAINT users_user_permissions_user_id_92473840_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict qjdbKeaICmRGaZAsm3nd8chQTELyU4VeSRemzUt0iLtZC3IoUtCMBoEOVXmJoOk

