from apps.jobs.models.application import Application
from apps.jobs.models.candidate import Candidate
from apps.jobs.models.company import Company
from apps.jobs.models.location import Location
from apps.jobs.models.offer import Offer
from apps.jobs.models.offer_technology import OfferTechnology
from apps.jobs.models.recruiter import Recruiter
from apps.jobs.models.technology import Technology
from apps.jobs.models.user import User
