# Generated by Django 5.2.14 on 2026-07-06 17:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='description',
        ),
        migrations.AddField(
            model_name='offer',
            name='description_detail',
            field=models.CharField(default='', max_length=2000, validators=[django.core.validators.MinLengthValidator(10)]),
            preserve_default=False,
        ),
    ]
