# Generated by Django 5.2.14 on 2026-07-19 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_offer_description_offer_description_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
