# Generated by Django 5.2.14 on 2026-07-19 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_candidate_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiter',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
